import type { CategoryKey } from './plants';

/**
 * The plant catalog: 1000+ common house and garden plants. Data only — all
 * care logic lives in lib/plants.ts, which expands each row into a complete,
 * measurable care profile from its category baseline (plus curated overrides).
 *
 * Row = [common name, latin name, category, emoji override?]. Common names are
 * unique (they key the lookup); latin names are real taxa or real, widely-sold
 * cultivars.
 */
export type Row = [string, string, CategoryKey, string?];

export const ROWS: Row[] = [
  // ═══════════════ HOUSEPLANTS — AROIDS & TROPICAL FOLIAGE ═══════════════
  ['Monstera', 'Monstera deliciosa', 'tropical', '🌿'],
  ['Swiss cheese vine', 'Monstera adansonii', 'tropical'],
  ['Monstera Thai Constellation', 'Monstera deliciosa "Thai Constellation"', 'tropical'],
  ['Monstera Albo', 'Monstera deliciosa "Albo Variegata"', 'tropical'],
  ['Monstera Siltepecana', 'Monstera siltepecana', 'vine', '🍃'],
  ['Monstera Standleyana', 'Monstera standleyana', 'vine', '🍃'],
  ['Monstera Dubia', 'Monstera dubia', 'vine', '🍃'],
  ['Monstera Pinnatipartita', 'Monstera pinnatipartita', 'tropical'],
  ['Mini monstera', 'Rhaphidophora tetrasperma', 'vine', '🍃'],
  ['Shingle plant', 'Rhaphidophora hayi', 'vine', '🍃'],
  ['Heartleaf philodendron', 'Philodendron hederaceum', 'vine', '🍃'],
  ['Philodendron Brasil', 'Philodendron hederaceum "Brasil"', 'vine', '🍃'],
  ['Philodendron Birkin', 'Philodendron "Birkin"', 'tropical'],
  ['Philodendron Pink Princess', 'Philodendron erubescens "Pink Princess"', 'tropical'],
  ['Philodendron Micans', 'Philodendron hederaceum var. hederaceum', 'vine', '🍃'],
  ['Philodendron Selloum', 'Thaumatophyllum bipinnatifidum', 'tropical'],
  ['Philodendron Gloriosum', 'Philodendron gloriosum', 'tropical'],
  ['Philodendron Melanochrysum', 'Philodendron melanochrysum', 'vine', '🍃'],
  ['Philodendron Prince of Orange', 'Philodendron "Prince of Orange"', 'tropical'],
  ['Philodendron Moonlight', 'Philodendron "Moonlight"', 'tropical'],
  ['Philodendron White Knight', 'Philodendron erubescens "White Knight"', 'vine', '🍃'],
  ['Philodendron White Princess', 'Philodendron erubescens "White Princess"', 'tropical'],
  ['Philodendron Billietiae', 'Philodendron billietiae', 'tropical'],
  ['Silver sword philodendron', 'Philodendron hastatum', 'vine', '🍃'],
  ['Philodendron Squamiferum', 'Philodendron squamiferum', 'vine', '🍃'],
  ['Philodendron Verrucosum', 'Philodendron verrucosum', 'tropical'],
  ['Philodendron Mamei', 'Philodendron mamei', 'tropical'],
  ['Philodendron Plowmanii', 'Philodendron plowmanii', 'tropical'],
  ['Philodendron Ring of Fire', 'Philodendron "Ring of Fire"', 'tropical'],
  ['Philodendron Brandtianum', 'Philodendron brandtianum', 'vine', '🍃'],
  ['Philodendron Xanadu', 'Thaumatophyllum xanadu', 'tropical'],
  ['Philodendron Rojo Congo', 'Philodendron "Rojo Congo"', 'tropical'],
  ['Philodendron Imperial Green', 'Philodendron "Imperial Green"', 'tropical'],
  ['Golden pothos', 'Epipremnum aureum', 'vine', '🍃'],
  ['Marble Queen pothos', 'Epipremnum aureum "Marble Queen"', 'vine', '🍃'],
  ['Neon pothos', 'Epipremnum aureum "Neon"', 'vine', '🍃'],
  ['Jade pothos', 'Epipremnum aureum "Jade"', 'vine', '🍃'],
  ['Manjula pothos', 'Epipremnum aureum "Manjula"', 'vine', '🍃'],
  ['Pearls and Jade pothos', 'Epipremnum aureum "Pearls and Jade"', 'vine', '🍃'],
  ["N'Joy pothos", 'Epipremnum aureum "N\'Joy"', 'vine', '🍃'],
  ['Global Green pothos', 'Epipremnum aureum "Global Green"', 'vine', '🍃'],
  ['Cebu Blue pothos', 'Epipremnum pinnatum "Cebu Blue"', 'vine', '🍃'],
  ['Baltic Blue pothos', 'Epipremnum pinnatum "Baltic Blue"', 'vine', '🍃'],
  ['Satin pothos', 'Scindapsus pictus', 'vine', '🍃'],
  ['Scindapsus Exotica', 'Scindapsus pictus "Exotica"', 'vine', '🍃'],
  ['Scindapsus Silvery Ann', 'Scindapsus pictus "Silvery Ann"', 'vine', '🍃'],
  ['Scindapsus Treubii Moonlight', 'Scindapsus treubii "Moonlight"', 'vine', '🍃'],
  ['Peace lily', 'Spathiphyllum wallisii', 'tropical', '🌸'],
  ['Peace lily Domino', 'Spathiphyllum "Domino"', 'tropical', '🌸'],
  ['Peace lily Sensation', 'Spathiphyllum "Sensation"', 'tropical', '🌸'],
  ['Chinese evergreen', 'Aglaonema commutatum', 'tropical'],
  ['Aglaonema Red Siam', 'Aglaonema "Siam Aurora"', 'tropical'],
  ['Aglaonema Silver Bay', 'Aglaonema "Silver Bay"', 'tropical'],
  ['Aglaonema Maria', 'Aglaonema "Maria"', 'tropical'],
  ['Aglaonema Cutlass', 'Aglaonema "Cutlass"', 'tropical'],
  ['Aglaonema Silver Queen', 'Aglaonema "Silver Queen"', 'tropical'],
  ['Aglaonema Pictum Tricolor', 'Aglaonema pictum "Tricolor"', 'tropical'],
  ['Dumb cane', 'Dieffenbachia seguine', 'tropical'],
  ['Dieffenbachia Camille', 'Dieffenbachia "Camille"', 'tropical'],
  ['Dieffenbachia Tropic Snow', 'Dieffenbachia "Tropic Snow"', 'tropical'],
  ['Arrowhead plant', 'Syngonium podophyllum', 'vine', '🍃'],
  ['Syngonium Albo', 'Syngonium podophyllum "Albo Variegatum"', 'vine', '🍃'],
  ['Syngonium Neon Robusta', 'Syngonium podophyllum "Neon Robusta"', 'vine', '🍃'],
  ['Syngonium Batik', 'Syngonium podophyllum "Batik"', 'vine', '🍃'],
  ['Syngonium Confetti', 'Syngonium podophyllum "Confetti"', 'vine', '🍃'],
  ['ZZ plant', 'Zamioculcas zamiifolia', 'tropical', '🌿'],
  ['Raven ZZ', 'Zamioculcas zamiifolia "Raven"', 'tropical'],
  ['Elephant ear', 'Alocasia amazonica', 'tropical'],
  ['Alocasia Polly', 'Alocasia × amazonica "Polly"', 'tropical'],
  ['Alocasia Zebrina', 'Alocasia zebrina', 'tropical'],
  ['Alocasia Frydek', 'Alocasia micholitziana "Frydek"', 'tropical'],
  ['Alocasia Silver Dragon', 'Alocasia baginda "Silver Dragon"', 'tropical'],
  ['Alocasia Dragon Scale', 'Alocasia baginda "Dragon Scale"', 'tropical'],
  ['Alocasia Cuprea', 'Alocasia cuprea', 'tropical'],
  ['Alocasia Black Velvet', 'Alocasia reginula "Black Velvet"', 'tropical'],
  ['Alocasia Stingray', 'Alocasia macrorrhizos "Stingray"', 'tropical'],
  ['Alocasia Regal Shield', 'Alocasia "Regal Shield"', 'tropical'],
  ['Alocasia Lauterbachiana', 'Alocasia lauterbachiana', 'tropical'],
  ['Alocasia Odora', 'Alocasia odora', 'tropical'],
  ['Giant taro', 'Alocasia macrorrhizos', 'tropical'],
  ['Colocasia', 'Colocasia esculenta', 'tropical'],
  ['Caladium', 'Caladium bicolor', 'tropical', '🌸'],
  ['Anthurium', 'Anthurium andraeanum', 'tropical', '🌸'],
  ['Anthurium Clarinervium', 'Anthurium clarinervium', 'tropical'],
  ['Anthurium Crystallinum', 'Anthurium crystallinum', 'tropical'],
  ['Anthurium Veitchii', 'Anthurium veitchii', 'tropical'],
  ['Anthurium Warocqueanum', 'Anthurium warocqueanum', 'tropical'],
  ['Anthurium Forgetii', 'Anthurium forgetii', 'tropical'],
  ['Flamingo flower', 'Anthurium scherzerianum', 'tropical', '🌸'],
  ['Anthurium Superbum', 'Anthurium superbum', 'tropical'],
  ['Anthurium Radicans', 'Anthurium radicans', 'tropical'],

  // ── Prayer plants & calatheas ──
  ['Calathea Orbifolia', 'Calathea orbifolia', 'tropical', '🪴'],
  ['Calathea Medallion', 'Goeppertia veitchiana', 'tropical', '🪴'],
  ['Rattlesnake plant', 'Goeppertia insignis', 'tropical', '🪴'],
  ['Calathea Zebrina', 'Goeppertia zebrina', 'tropical', '🪴'],
  ['Peacock plant', 'Goeppertia makoyana', 'tropical', '🪴'],
  ['Calathea Roseopicta', 'Goeppertia roseopicta', 'tropical', '🪴'],
  ['Calathea Dottie', 'Goeppertia roseopicta "Dottie"', 'tropical', '🪴'],
  ['Calathea Rosy', 'Goeppertia roseopicta "Rosy"', 'tropical', '🪴'],
  ['Calathea Warscewiczii', 'Goeppertia warszewiczii', 'tropical', '🪴'],
  ['Calathea Ornata', 'Goeppertia ornata', 'tropical', '🪴'],
  ['Calathea Rufibarba', 'Goeppertia rufibarba', 'tropical', '🪴'],
  ['Calathea White Fusion', 'Goeppertia "White Fusion"', 'tropical', '🪴'],
  ['Calathea Network', 'Goeppertia kegeljanii "Network"', 'tropical', '🪴'],
  ['Calathea Freddie', 'Goeppertia concinna "Freddie"', 'tropical', '🪴'],
  ['Prayer plant', 'Maranta leuconeura', 'tropical', '🪴'],
  ['Lemon lime prayer plant', 'Maranta leuconeura "Lemon Lime"', 'tropical', '🪴'],
  ['Stromanthe Triostar', 'Stromanthe sanguinea', 'tropical'],
  ['Ctenanthe', 'Ctenanthe burle-marxii', 'tropical'],
  ['Never never plant', 'Ctenanthe oppenheimiana', 'tropical'],

  // ── Small foliage & gesneriads ──
  ['Nerve plant', 'Fittonia albivenis', 'tropical'],
  ['Polka dot plant', 'Hypoestes phyllostachya', 'tropical'],
  ['Aluminum plant', 'Pilea cadierei', 'tropical'],
  ['Chinese money plant', 'Pilea peperomioides', 'tropical'],
  ['Friendship plant', 'Pilea involucrata', 'tropical'],
  ['Pilea Glauca', 'Pilea glauca', 'vine', '🍃'],
  ['Artillery plant', 'Pilea microphylla', 'tropical'],
  ['Creeping Charlie', 'Pilea nummulariifolia', 'vine', '🍃'],
  ['Baby tears', 'Soleirolia soleirolii', 'tropical'],
  ['African violet', 'Saintpaulia ionantha', 'flowering', '🌸'],
  ['Cape primrose', 'Streptocarpus × hybridus', 'flowering', '🌸'],
  ['Gloxinia', 'Sinningia speciosa', 'flowering', '🌸'],
  ['Lipstick plant', 'Aeschynanthus radicans', 'vine', '🌸'],
  ['Goldfish plant', 'Nematanthus gregarius', 'vine', '🌸'],
  ['Flame violet', 'Episcia cupreata', 'tropical', '🌸'],
  ['Purple passion plant', 'Gynura aurantiaca', 'tropical'],
  ['Piggyback plant', 'Tolmiea menziesii', 'tropical'],
  ['Oxalis triangularis', 'Oxalis triangularis', 'tropical', '💜'],
  ['Zebra plant', 'Aphelandra squarrosa', 'tropical'],
  ['Mosaic plant', 'Fittonia albivenis "Argyroneura"', 'tropical'],

  // ── Peperomias ──
  ['Watermelon peperomia', 'Peperomia argyreia', 'tropical'],
  ['Peperomia Obtusifolia', 'Peperomia obtusifolia', 'tropical'],
  ['Ripple peperomia', 'Peperomia caperata', 'tropical'],
  ['Peperomia Rosso', 'Peperomia caperata "Rosso"', 'tropical'],
  ['Peperomia Frost', 'Peperomia caperata "Frost"', 'tropical'],
  ['Peperomia Napoli Nights', 'Peperomia "Napoli Nights"', 'tropical'],
  ['Peperomia Hope', 'Peperomia tetraphylla "Hope"', 'vine', '🍃'],
  ['Peperomia Ruby Cascade', 'Peperomia "Ruby Cascade"', 'vine', '🍃'],
  ['Raindrop peperomia', 'Peperomia polybotrya', 'tropical'],
  ['Peperomia Jelly', 'Peperomia clusiifolia "Jelly"', 'tropical'],
  ['Ruby glow peperomia', 'Peperomia graveolens', 'succulent'],
  ['Parallel peperomia', 'Peperomia puteolata', 'vine', '🍃'],
  ['Felted peperomia', 'Peperomia incana', 'tropical'],
  ['Trailing jade peperomia', 'Peperomia rotundifolia', 'vine', '🍃'],
  ['String of turtles', 'Peperomia prostrata', 'vine', '🍃'],
  ['Baby rubber plant', 'Peperomia obtusifolia "Variegata"', 'tropical'],

  // ── Classic foliage ──
  ['Cast iron plant', 'Aspidistra elatior', 'tropical'],
  ['Ti plant', 'Cordyline fruticosa', 'tropical'],
  ['Cabbage tree', 'Cordyline australis', 'tree'],
  ['Croton', 'Codiaeum variegatum', 'tropical'],
  ['Croton Petra', 'Codiaeum variegatum "Petra"', 'tropical'],
  ['Croton Mammy', 'Codiaeum variegatum "Mammy"', 'tropical'],
  ['Coleus', 'Coleus scutellarioides', 'flowering'],
  ['Bird of paradise', 'Strelitzia reginae', 'tropical', '🌸'],
  ['White bird of paradise', 'Strelitzia nicolai', 'tropical'],
  ['Banana plant', 'Musa acuminata', 'tropical'],
  ['Ornamental banana', 'Musa "Dwarf Cavendish"', 'tropical'],
  ['Ginger', 'Zingiber officinale', 'tropical'],
  ['Turmeric', 'Curcuma longa', 'tropical'],
  ['Fatsia', 'Fatsia japonica', 'tropical'],
  ['False aralia', 'Plerandra elegantissima', 'tropical'],
  ['Ming aralia', 'Polyscias fruticosa', 'tropical'],
  ['Balfour aralia', 'Polyscias scutellaria', 'tropical'],
  ['Buddhist pine', 'Podocarpus macrophyllus', 'tree', '🌲'],
  ['Silver dollar eucalyptus', 'Eucalyptus cinerea', 'tree'],

  // ── Bromeliads & air plants ──
  ['Bromeliad', 'Guzmania lingulata', 'tropical', '🌸'],
  ['Aechmea', 'Aechmea fasciata', 'tropical', '🌸'],
  ['Neoregelia', 'Neoregelia carolinae', 'tropical'],
  ['Flaming sword', 'Vriesea splendens', 'tropical', '🌸'],
  ['Earth star', 'Cryptanthus bivittatus', 'tropical'],
  ['Queen’s tears', 'Billbergia nutans', 'tropical', '🌸'],
  ['Air plant', 'Tillandsia ionantha', 'tropical'],
  ['Tillandsia Xerographica', 'Tillandsia xerographica', 'tropical'],
  ['Spanish moss', 'Tillandsia usneoides', 'tropical'],

  // ═══════════════ FERNS ═══════════════
  ['Boston fern', 'Nephrolepis exaltata', 'fern', '🌱'],
  ['Kimberly Queen fern', 'Nephrolepis obliterata', 'fern', '🌱'],
  ['Bird’s nest fern', 'Asplenium nidus', 'fern', '🌱'],
  ['Staghorn fern', 'Platycerium bifurcatum', 'fern'],
  ['Maidenhair fern', 'Adiantum raddianum', 'fern'],
  ['Rabbit’s foot fern', 'Davallia fejeensis', 'fern'],
  ['Blue star fern', 'Phlebodium aureum', 'fern'],
  ['Button fern', 'Pellaea rotundifolia', 'fern'],
  ['Autumn fern', 'Dryopteris erythrosora', 'fern'],
  ['Asparagus fern', 'Asparagus setaceus', 'fern'],
  ['Foxtail fern', 'Asparagus densiflorus', 'fern'],
  ['Lemon button fern', 'Nephrolepis cordifolia', 'fern', '🌱'],
  ['Crocodile fern', 'Microsorum musifolium', 'fern'],
  ['Japanese painted fern', 'Athyrium niponicum', 'fern'],
  ['Holly fern', 'Cyrtomium falcatum', 'fern'],
  ['Silver brake fern', 'Pteris cretica', 'fern'],
  ['Heart fern', 'Hemionitis arifolia', 'fern'],
  ['Ostrich fern', 'Matteuccia struthiopteris', 'fern'],
  ['Cinnamon fern', 'Osmundastrum cinnamomeum', 'fern'],
  ['Royal fern', 'Osmunda regalis', 'fern'],
  ['Australian tree fern', 'Cyathea cooperi', 'fern'],
  ['Squirrel’s foot fern', 'Davallia canariensis', 'fern'],
  ['Club moss', 'Selaginella kraussiana', 'fern'],
  ['Christmas fern', 'Polystichum acrostichoides', 'fern'],
  ['Lady fern', 'Athyrium filix-femina', 'fern'],

  // ═══════════════ PALMS ═══════════════
  ['Areca palm', 'Dypsis lutescens', 'palm', '🌴'],
  ['Parlor palm', 'Chamaedorea elegans', 'palm', '🌴'],
  ['Kentia palm', 'Howea forsteriana', 'palm', '🌴'],
  ['Majesty palm', 'Ravenea rivularis', 'palm', '🌴'],
  ['Ponytail palm', 'Beaucarnea recurvata', 'succulent'],
  ['Cat palm', 'Chamaedorea cataractarum', 'palm', '🌴'],
  ['Sago palm', 'Cycas revoluta', 'palm', '🌴'],
  ['Fishtail palm', 'Caryota mitis', 'palm', '🌴'],
  ['Lady palm', 'Rhapis excelsa', 'palm', '🌴'],
  ['Chinese fan palm', 'Livistona chinensis', 'palm', '🌴'],
  ['Bamboo palm', 'Chamaedorea seifrizii', 'palm', '🌴'],
  ['Pygmy date palm', 'Phoenix roebelenii', 'palm', '🌴'],
  ['Windmill palm', 'Trachycarpus fortunei', 'palm', '🌴'],
  ['European fan palm', 'Chamaerops humilis', 'palm', '🌴'],
  ['Bismarck palm', 'Bismarckia nobilis', 'palm', '🌴'],
  ['Pindo palm', 'Butia capitata', 'palm', '🌴'],
  ['Mexican fan palm', 'Washingtonia robusta', 'palm', '🌴'],

  // ═══════════════ DRACAENAS, SNAKE PLANTS & SPIDER PLANTS ═══════════════
  ['Snake plant', 'Dracaena trifasciata', 'succulent', '🌵'],
  ['Snake plant Laurentii', 'Dracaena trifasciata "Laurentii"', 'succulent', '🌵'],
  ['Snake plant Moonshine', 'Dracaena trifasciata "Moonshine"', 'succulent', '🌵'],
  ['Snake plant Black Coral', 'Dracaena trifasciata "Black Coral"', 'succulent', '🌵'],
  ['Snake plant Fernwood', 'Dracaena "Fernwood Mikado"', 'succulent', '🌵'],
  ['Whale fin snake plant', 'Dracaena masoniana', 'succulent', '🌵'],
  ['Cylindrical snake plant', 'Dracaena angolensis', 'succulent', '🌵'],
  ['Dragon tree', 'Dracaena marginata', 'tree'],
  ['Corn plant', 'Dracaena fragrans', 'tree'],
  ['Janet Craig', 'Dracaena deremensis "Janet Craig"', 'tropical'],
  ['Dracaena Lemon Lime', 'Dracaena deremensis "Lemon Lime"', 'tropical'],
  ['Dracaena Warneckii', 'Dracaena deremensis "Warneckii"', 'tropical'],
  ['Song of India', 'Dracaena reflexa "Variegata"', 'tropical'],
  ['Lucky bamboo', 'Dracaena sanderiana', 'grass', '🎋'],
  ['Spider plant', 'Chlorophytum comosum', 'grass', '🌿'],
  ['Spider plant Bonnie', 'Chlorophytum comosum "Bonnie"', 'grass', '🌿'],
  ['Variegated spider plant', 'Chlorophytum comosum "Vittatum"', 'grass', '🌿'],

  // ═══════════════ INDOOR TREES & FIGS ═══════════════
  ['Fiddle-leaf fig', 'Ficus lyrata', 'tree', '🌳'],
  ['Fiddle-leaf fig Bambino', 'Ficus lyrata "Bambino"', 'tree', '🌳'],
  ['Rubber plant', 'Ficus elastica', 'tree', '🌳'],
  ['Rubber plant Tineke', 'Ficus elastica "Tineke"', 'tree', '🌳'],
  ['Rubber plant Ruby', 'Ficus elastica "Ruby"', 'tree', '🌳'],
  ['Rubber plant Burgundy', 'Ficus elastica "Burgundy"', 'tree', '🌳'],
  ['Weeping fig', 'Ficus benjamina', 'tree', '🌳'],
  ['Ficus Audrey', 'Ficus benghalensis', 'tree', '🌳'],
  ['Ficus Alii', 'Ficus maclellandii "Alii"', 'tree', '🌳'],
  ['Triangle ficus', 'Ficus triangularis', 'tree', '🌳'],
  ['Creeping fig', 'Ficus pumila', 'vine', '🍃'],
  ['Umbrella tree', 'Schefflera actinophylla', 'tree'],
  ['Dwarf umbrella tree', 'Schefflera arboricola', 'tree'],
  ['Money tree', 'Pachira aquatica', 'tree', '🌳'],
  ['Norfolk Island pine', 'Araucaria heterophylla', 'tree', '🌲'],
  ['Guiana chestnut', 'Pachira glabra', 'tree', '🌳'],
  ['Jade plant', 'Crassula ovata', 'succulent'],
  ['Olive tree', 'Olea europaea', 'tree', '🫒'],
  ['Meyer lemon', 'Citrus × meyeri', 'tree', '🍋'],
  ['Calamondin orange', 'Citrus × microcarpa', 'tree', '🍊'],
  ['Kumquat', 'Citrus japonica', 'tree', '🍊'],
  ['Kaffir lime', 'Citrus hystrix', 'tree'],
  ['Key lime', 'Citrus × aurantiifolia', 'tree', '🍋'],
  ['Coffee plant', 'Coffea arabica', 'tree'],
  ['Avocado', 'Persea americana', 'tree', '🥑'],
  ['Yucca cane', 'Yucca gigantea', 'tree'],
  ['Dwarf pomegranate', 'Punica granatum "Nana"', 'tree'],

  // ═══════════════ SUCCULENTS ═══════════════
  ['Aloe vera', 'Aloe vera', 'succulent'],
  ['Lace aloe', 'Aristaloe aristata', 'succulent'],
  ['Tiger tooth aloe', 'Aloe juvenna', 'succulent'],
  ['Aloe Christmas Carol', 'Aloe "Christmas Carol"', 'succulent'],
  ['Short-leaved aloe', 'Aloe brevifolia', 'succulent'],
  ['Haworthia', 'Haworthiopsis attenuata', 'succulent'],
  ['Zebra haworthia', 'Haworthiopsis fasciata', 'succulent'],
  ['Haworthia Cooperi', 'Haworthia cooperi', 'succulent'],
  ['Horse’s teeth haworthia', 'Haworthia truncata', 'succulent'],
  ['Echeveria', 'Echeveria elegans', 'succulent'],
  ['Echeveria Lola', 'Echeveria "Lola"', 'succulent'],
  ['Echeveria Perle von Nurnberg', 'Echeveria "Perle von Nürnberg"', 'succulent'],
  ['Echeveria Black Prince', 'Echeveria "Black Prince"', 'succulent'],
  ['Echeveria Agavoides', 'Echeveria agavoides', 'succulent'],
  ['Echeveria Topsy Turvy', 'Echeveria runyonii "Topsy Turvy"', 'succulent'],
  ['Plush plant', 'Echeveria pulvinata', 'succulent'],
  ['Ghost plant', 'Graptopetalum paraguayense', 'succulent'],
  ['Graptoveria Fred Ives', '× Graptoveria "Fred Ives"', 'succulent'],
  ['Moonstones', 'Pachyphytum oviferum', 'succulent'],
  ['Panda plant', 'Kalanchoe tomentosa', 'succulent'],
  ['Mother of thousands', 'Kalanchoe daigremontiana', 'succulent'],
  ['Paddle plant', 'Kalanchoe luciae', 'succulent'],
  ['Felt bush', 'Kalanchoe beharensis', 'succulent'],
  ['Flaming Katy', 'Kalanchoe blossfeldiana', 'flowering', '🌸'],
  ['Burro’s tail', 'Sedum morganianum', 'succulent'],
  ['Jelly bean plant', 'Sedum rubrotinctum', 'succulent'],
  ['Sedum Angelina', 'Sedum rupestre "Angelina"', 'succulent'],
  ['Dragon’s blood sedum', 'Phedimus spurius "Dragon\'s Blood"', 'succulent'],
  ['String of pearls', 'Curio rowleyanus', 'vine', '🍃'],
  ['String of bananas', 'Curio radicans', 'vine', '🍃'],
  ['String of hearts', 'Ceropegia woodii', 'vine', '🍃'],
  ['String of dolphins', 'Curio × peregrinus', 'vine', '🍃'],
  ['String of buttons', 'Crassula perforata', 'succulent'],
  ['Ruby necklace', 'Othonna capensis', 'vine', '🍃'],
  ['Blue chalksticks', 'Curio repens', 'succulent'],
  ['Blue chalk fingers', 'Curio talinoides var. mandraliscae', 'succulent'],
  ['Hens and chicks', 'Sempervivum tectorum', 'succulent'],
  ['Cobweb houseleek', 'Sempervivum arachnoideum', 'succulent'],
  ['Aeonium', 'Aeonium arboreum', 'succulent'],
  ['Aeonium Zwartkop', 'Aeonium arboreum "Zwartkop"', 'succulent'],
  ['Aeonium Kiwi', 'Aeonium "Kiwi"', 'succulent'],
  ['Crown of thorns', 'Euphorbia milii', 'succulent', '🌸'],
  ['Pencil cactus', 'Euphorbia tirucalli', 'succulent'],
  ['African milk tree', 'Euphorbia trigona', 'succulent'],
  ['Baseball plant', 'Euphorbia obesa', 'succulent'],
  ['Dragon bones', 'Euphorbia lactea', 'succulent'],
  ['Lithops', 'Lithops spp.', 'succulent'],
  ['Baby toes', 'Fenestraria rhopalophylla', 'succulent'],
  ['Split rock', 'Pleiospilos nelii', 'succulent'],
  ['Sand rose', 'Anacampseros rufescens', 'succulent'],
  ['Ice plant', 'Delosperma cooperi', 'succulent', '🌸'],
  ['Snake gourd agave', 'Agave attenuata', 'succulent'],
  ['Century plant', 'Agave americana', 'succulent'],
  ['Queen Victoria agave', 'Agave victoriae-reginae', 'succulent'],
  ['Parry’s agave', 'Agave parryi', 'succulent'],
  ['Agave Blue Glow', 'Agave "Blue Glow"', 'succulent'],
  ['Elephant bush', 'Portulacaria afra', 'succulent'],
  ['Rainbow bush', 'Portulacaria afra "Variegata"', 'succulent'],
  ['Gollum jade', 'Crassula ovata "Gollum"', 'succulent'],
  ['Campfire crassula', 'Crassula capitella "Campfire"', 'succulent'],
  ['Silver dollar jade', 'Crassula arborescens', 'succulent'],
  ['Ox tongue', 'Gasteria bicolor', 'succulent'],
  ['Bear paw', 'Cotyledon tomentosa', 'succulent'],
  ['Pig’s ear', 'Cotyledon orbiculata', 'succulent'],
  ['Starfish flower', 'Stapelia gigantea', 'succulent'],
  ['Lifesaver plant', 'Huernia zebrina', 'succulent'],
  ['Desert rose', 'Adenium obesum', 'succulent', '🌸'],
  ['Christmas cactus', 'Schlumbergera bridgesii', 'succulent', '🌸'],
  ['Thanksgiving cactus', 'Schlumbergera truncata', 'succulent', '🌸'],
  ['Easter cactus', 'Schlumbergera gaertneri', 'succulent', '🌸'],
  ['Hoya Kerrii', 'Hoya kerrii', 'succulent'],

  // ═══════════════ CACTI ═══════════════
  ['Bunny ears cactus', 'Opuntia microdasys', 'cactus', '🌵'],
  ['Golden barrel cactus', 'Echinocactus grusonii', 'cactus', '🌵'],
  ['Old lady cactus', 'Mammillaria hahniana', 'cactus', '🌵'],
  ['Ladyfinger cactus', 'Mammillaria elongata', 'cactus', '🌵'],
  ['Fairy castle cactus', 'Acanthocereus tetragonus', 'cactus', '🌵'],
  ['Moon cactus', 'Gymnocalycium mihanovichii', 'cactus', '🌵'],
  ['Dwarf chin cactus', 'Gymnocalycium baldianum', 'cactus', '🌵'],
  ['San Pedro cactus', 'Echinopsis pachanoi', 'cactus', '🌵'],
  ['Easter lily cactus', 'Echinopsis oxygona', 'cactus', '🌵'],
  ['Prickly pear', 'Opuntia ficus-indica', 'cactus', '🌵'],
  ['Purple prickly pear', 'Opuntia santa-rita', 'cactus', '🌵'],
  ['Star cactus', 'Astrophytum asterias', 'cactus', '🌵'],
  ['Bishop’s cap cactus', 'Astrophytum myriostigma', 'cactus', '🌵'],
  ['Rat tail cactus', 'Disocactus flagelliformis', 'cactus', '🌵'],
  ['Fishbone cactus', 'Disocactus anguliger', 'cactus', '🌵'],
  ['Orchid cactus', 'Epiphyllum hybridus', 'cactus', '🌸'],
  ['Queen of the night', 'Epiphyllum oxypetalum', 'cactus', '🌵'],
  ['Mistletoe cactus', 'Rhipsalis baccifera', 'cactus', '🌵'],
  ['Dancing bones', 'Hatiora salicornioides', 'cactus', '🌵'],
  ['Peruvian apple cactus', 'Cereus repandus', 'cactus', '🌵'],
  ['Blue candle cactus', 'Myrtillocactus geometrizans', 'cactus', '🌵'],
  ['Silver torch cactus', 'Cleistocactus strausii', 'cactus', '🌵'],
  ['Old man cactus', 'Cephalocereus senilis', 'cactus', '🌵'],
  ['Peruvian old lady cactus', 'Espostoa lanata', 'cactus', '🌵'],
  ['Golden ball cactus', 'Parodia leninghausii', 'cactus', '🌵'],
  ['Crown cactus', 'Rebutia minuscula', 'cactus', '🌵'],
  ['Fishhook barrel cactus', 'Ferocactus wislizeni', 'cactus', '🌵'],
  ['Blue columnar cactus', 'Pilosocereus pachycladus', 'cactus', '🌵'],
  ['Paper spine cactus', 'Tephrocactus articulatus', 'cactus', '🌵'],
  ['Christmas cheer', 'Mammillaria spinosissima', 'cactus', '🌵'],

  // ═══════════════ HOUSEPLANT VINES, HOYAS & IVIES ═══════════════
  ['English ivy', 'Hedera helix', 'vine', '🍃'],
  ['Needlepoint ivy', 'Hedera helix "Needlepoint"', 'vine', '🍃'],
  ['Glacier ivy', 'Hedera helix "Glacier"', 'vine', '🍃'],
  ['Algerian ivy', 'Hedera algeriensis', 'vine', '🍃'],
  ['Swedish ivy', 'Plectranthus verticillatus', 'vine', '🍃'],
  ['Grape ivy', 'Cissus rhombifolia', 'vine', '🍃'],
  ['Rex begonia vine', 'Cissus discolor', 'vine', '🍃'],
  ['Wandering jew', 'Tradescantia zebrina', 'vine', '🍃'],
  ['Tradescantia Nanouk', 'Tradescantia albiflora "Nanouk"', 'vine', '🍃'],
  ['Purple heart', 'Tradescantia pallida', 'vine', '🍃'],
  ['White velvet tradescantia', 'Tradescantia sillamontana', 'vine', '🍃'],
  ['Moses in the cradle', 'Tradescantia spathacea', 'tropical'],
  ['Turtle vine', 'Callisia repens', 'vine', '🍃'],
  ['Maidenhair vine', 'Muehlenbeckia complexa', 'vine', '🍃'],
  ['String of nickels', 'Dischidia nummularia', 'vine', '🍃'],
  ['Hoya', 'Hoya carnosa', 'vine', '🍃'],
  ['Hoya Krimson Queen', 'Hoya carnosa "Krimson Queen"', 'vine', '🍃'],
  ['Hoya Krimson Princess', 'Hoya carnosa "Krimson Princess"', 'vine', '🍃'],
  ['Hindu rope hoya', 'Hoya carnosa "Compacta"', 'vine', '🍃'],
  ['Wax plant', 'Hoya pubicalyx', 'vine', '🍃'],
  ['Hoya Australis', 'Hoya australis', 'vine', '🍃'],
  ['Hoya Obovata', 'Hoya obovata', 'vine', '🍃'],
  ['Hoya Linearis', 'Hoya linearis', 'vine', '🍃'],
  ['Hoya Bella', 'Hoya bella', 'vine', '🍃'],
  ['Hoya Retusa', 'Hoya retusa', 'vine', '🍃'],
  ['Hoya Curtisii', 'Hoya curtisii', 'vine', '🍃'],
  ['Hoya Macrophylla', 'Hoya macrophylla', 'vine', '🍃'],
  ['Hoya Callistophylla', 'Hoya callistophylla', 'vine', '🍃'],
  ['Hoya Finlaysonii', 'Hoya finlaysonii', 'vine', '🍃'],
  ['Hoya Lacunosa', 'Hoya lacunosa', 'vine', '🍃'],
  ['Hoya Wayetii', 'Hoya wayetii', 'vine', '🍃'],
  ['Hoya Shepherdii', 'Hoya shepherdii', 'vine', '🍃'],
  ['Hoya Mathilde', 'Hoya "Mathilde"', 'vine', '🍃'],
  ['Passionflower', 'Passiflora caerulea', 'vine', '🌸'],
  ['Bougainvillea', 'Bougainvillea glabra', 'vine', '🌸'],
  ['Mandevilla', 'Mandevilla sanderi', 'vine', '🌸'],
  ['Morning glory', 'Ipomoea purpurea', 'vine', '🌸'],
  ['Jasmine', 'Jasminum polyanthum', 'vine', '🌸'],
  ['Clematis', 'Clematis "Jackmanii"', 'vine', '🌸'],

  // ═══════════════ BEGONIAS ═══════════════
  ['Begonia', 'Begonia × semperflorens', 'flowering', '🌸'],
  ['Rex begonia', 'Begonia rex', 'flowering'],
  ['Polka dot begonia', 'Begonia maculata', 'flowering', '🌸'],
  ['Iron cross begonia', 'Begonia masoniana', 'flowering'],
  ['Angel wing begonia', 'Begonia coccinea', 'flowering', '🌸'],
  ['Dragon wing begonia', 'Begonia "Dragon Wing Red"', 'flowering', '🌸'],
  ['Escargot begonia', 'Begonia rex "Escargot"', 'flowering'],
  ['Begonia Listada', 'Begonia listada', 'flowering'],
  ['Begonia Lucerna', 'Begonia "Lucerna"', 'flowering', '🌸'],
  ['Tuberous begonia', 'Begonia × tuberhybrida', 'flowering', '🌸'],
  ['Bolivian begonia', 'Begonia boliviensis', 'flowering', '🌸'],

  // ═══════════════ HERBS ═══════════════
  ['Basil', 'Ocimum basilicum', 'herb', '🌿'],
  ['Genovese basil', 'Ocimum basilicum "Genovese"', 'herb', '🌿'],
  ['Thai basil', 'Ocimum basilicum var. thyrsiflora', 'herb', '🌿'],
  ['Lemon basil', 'Ocimum × citriodorum', 'herb', '🌿'],
  ['Purple basil', 'Ocimum basilicum "Purpurascens"', 'herb', '🌿'],
  ['Holy basil', 'Ocimum tenuiflorum', 'herb', '🌿'],
  ['Rosemary', 'Salvia rosmarinus', 'herb', '🌿'],
  ['Thyme', 'Thymus vulgaris', 'herb', '🌿'],
  ['Lemon thyme', 'Thymus × citriodorus', 'herb', '🌿'],
  ['Creeping thyme', 'Thymus serpyllum', 'herb', '🌿'],
  ['Oregano', 'Origanum vulgare', 'herb', '🌿'],
  ['Marjoram', 'Origanum majorana', 'herb', '🌿'],
  ['Mint', 'Mentha spicata', 'herb', '🌿'],
  ['Peppermint', 'Mentha × piperita', 'herb', '🌿'],
  ['Chocolate mint', 'Mentha × piperita "Chocolate"', 'herb', '🌿'],
  ['Apple mint', 'Mentha suaveolens', 'herb', '🌿'],
  ['Orange mint', 'Mentha × piperita citrata', 'herb', '🌿'],
  ['Parsley', 'Petroselinum crispum', 'herb', '🌿'],
  ['Italian parsley', 'Petroselinum crispum var. neapolitanum', 'herb', '🌿'],
  ['Cilantro', 'Coriandrum sativum', 'herb', '🌿'],
  ['Dill', 'Anethum graveolens', 'herb', '🌿'],
  ['Chives', 'Allium schoenoprasum', 'herb', '🌿'],
  ['Garlic chives', 'Allium tuberosum', 'herb', '🌿'],
  ['Sage', 'Salvia officinalis', 'herb', '🌿'],
  ['Purple sage', 'Salvia officinalis "Purpurascens"', 'herb', '🌿'],
  ['Tricolor sage', 'Salvia officinalis "Tricolor"', 'herb', '🌿'],
  ['Lavender', 'Lavandula angustifolia', 'herb', '💜'],
  ['French lavender', 'Lavandula stoechas', 'herb', '💜'],
  ['Lavender Grosso', 'Lavandula × intermedia "Grosso"', 'herb', '💜'],
  ['Lemongrass', 'Cymbopogon citratus', 'grass', '🌿'],
  ['Lemon balm', 'Melissa officinalis', 'herb', '🌿'],
  ['Lemon verbena', 'Aloysia citrodora', 'herb', '🌿'],
  ['Tarragon', 'Artemisia dracunculus', 'herb', '🌿'],
  ['Fennel', 'Foeniculum vulgare', 'herb', '🌿'],
  ['Catnip', 'Nepeta cataria', 'herb', '🌿'],
  ['Stevia', 'Stevia rebaudiana', 'herb', '🌿'],
  ['Bay laurel', 'Laurus nobilis', 'herb', '🌿'],
  ['German chamomile', 'Matricaria chamomilla', 'herb', '🌼'],
  ['Roman chamomile', 'Chamaemelum nobile', 'herb', '🌼'],
  ['Lovage', 'Levisticum officinale', 'herb', '🌿'],
  ['Sorrel', 'Rumex acetosa', 'herb', '🌿'],
  ['Summer savory', 'Satureja hortensis', 'herb', '🌿'],
  ['Winter savory', 'Satureja montana', 'herb', '🌿'],
  ['Chervil', 'Anthriscus cerefolium', 'herb', '🌿'],
  ['Borage', 'Borago officinalis', 'herb', '🌸'],
  ['Shiso', 'Perilla frutescens', 'herb', '🌿'],
  ['Curry leaf', 'Murraya koenigii', 'herb', '🌿'],
  ['Hyssop', 'Hyssopus officinalis', 'herb', '🌿'],
  ['Anise hyssop', 'Agastache foeniculum', 'herb', '💜'],
  ['Feverfew', 'Tanacetum parthenium', 'herb', '🌼'],
  ['Valerian', 'Valeriana officinalis', 'herb', '🌿'],
  ['Angelica', 'Angelica archangelica', 'herb', '🌿'],
  ['Salad burnet', 'Sanguisorba minor', 'herb', '🌿'],
  ['Vietnamese coriander', 'Persicaria odorata', 'herb', '🌿'],
  ['Epazote', 'Dysphania ambrosioides', 'herb', '🌿'],
  ['Rue', 'Ruta graveolens', 'herb', '🌿'],

  // ═══════════════ VEGETABLES ═══════════════
  ['Cherry tomato', 'Solanum lycopersicum', 'vegetable', '🍅'],
  ['Beefsteak tomato', 'Solanum lycopersicum "Beefsteak"', 'vegetable', '🍅'],
  ['Roma tomato', 'Solanum lycopersicum "Roma"', 'vegetable', '🍅'],
  ['San Marzano tomato', 'Solanum lycopersicum "San Marzano"', 'vegetable', '🍅'],
  ['Brandywine tomato', 'Solanum lycopersicum "Brandywine"', 'vegetable', '🍅'],
  ['Sungold tomato', 'Solanum lycopersicum "Sungold"', 'vegetable', '🍅'],
  ['Better Boy tomato', 'Solanum lycopersicum "Better Boy"', 'vegetable', '🍅'],
  ['Early Girl tomato', 'Solanum lycopersicum "Early Girl"', 'vegetable', '🍅'],
  ['Green Zebra tomato', 'Solanum lycopersicum "Green Zebra"', 'vegetable', '🍅'],
  ['Black Krim tomato', 'Solanum lycopersicum "Black Krim"', 'vegetable', '🍅'],
  ['Bell pepper', 'Capsicum annuum', 'vegetable', '🫑'],
  ['Chili pepper', 'Capsicum frutescens', 'vegetable', '🌶️'],
  ['Jalapeño', 'Capsicum annuum "Jalapeño"', 'vegetable', '🌶️'],
  ['Habanero', 'Capsicum chinense "Habanero"', 'vegetable', '🌶️'],
  ['Cayenne pepper', 'Capsicum annuum "Cayenne"', 'vegetable', '🌶️'],
  ['Serrano pepper', 'Capsicum annuum "Serrano"', 'vegetable', '🌶️'],
  ['Poblano pepper', 'Capsicum annuum "Poblano"', 'vegetable', '🌶️'],
  ['Banana pepper', 'Capsicum annuum "Banana"', 'vegetable', '🌶️'],
  ['Ghost pepper', 'Capsicum chinense "Bhut Jolokia"', 'vegetable', '🌶️'],
  ['Shishito pepper', 'Capsicum annuum "Shishito"', 'vegetable', '🌶️'],
  ['Thai chili', 'Capsicum annuum "Bird\'s Eye"', 'vegetable', '🌶️'],
  ['Cucumber', 'Cucumis sativus', 'vegetable', '🥒'],
  ['Pickling cucumber', 'Cucumis sativus "National Pickling"', 'vegetable', '🥒'],
  ['Armenian cucumber', 'Cucumis melo var. flexuosus', 'vegetable', '🥒'],
  ['Lettuce', 'Lactuca sativa', 'vegetable', '🥬'],
  ['Romaine lettuce', 'Lactuca sativa var. longifolia', 'vegetable', '🥬'],
  ['Butterhead lettuce', 'Lactuca sativa "Buttercrunch"', 'vegetable', '🥬'],
  ['Red leaf lettuce', 'Lactuca sativa "Red Sails"', 'vegetable', '🥬'],
  ['Iceberg lettuce', 'Lactuca sativa "Iceberg"', 'vegetable', '🥬'],
  ['Spinach', 'Spinacia oleracea', 'vegetable', '🥬'],
  ['Malabar spinach', 'Basella alba', 'vegetable', '🥬'],
  ['Kale', 'Brassica oleracea', 'vegetable', '🥬'],
  ['Lacinato kale', 'Brassica oleracea "Lacinato"', 'vegetable', '🥬'],
  ['Red Russian kale', 'Brassica oleracea "Red Russian"', 'vegetable', '🥬'],
  ['Arugula', 'Eruca vesicaria', 'vegetable', '🥬'],
  ['Swiss chard', 'Beta vulgaris', 'vegetable', '🥬'],
  ['Bright Lights chard', 'Beta vulgaris "Bright Lights"', 'vegetable', '🥬'],
  ['Mustard greens', 'Brassica juncea', 'vegetable', '🥬'],
  ['Watercress', 'Nasturtium officinale', 'vegetable', '🥬'],
  ['Mizuna', 'Brassica rapa var. niposinica', 'vegetable', '🥬'],
  ['Tatsoi', 'Brassica rapa var. rosularis', 'vegetable', '🥬'],
  ['Endive', 'Cichorium endivia', 'vegetable', '🥬'],
  ['Broccoli', 'Brassica oleracea var. italica', 'vegetable', '🥦'],
  ['Broccolini', 'Brassica oleracea "Broccolini"', 'vegetable', '🥦'],
  ['Romanesco', 'Brassica oleracea "Romanesco"', 'vegetable', '🥦'],
  ['Cauliflower', 'Brassica oleracea var. botrytis', 'vegetable', '🥦'],
  ['Cabbage', 'Brassica oleracea var. capitata', 'vegetable', '🥬'],
  ['Red cabbage', 'Brassica oleracea "Red Acre"', 'vegetable', '🥬'],
  ['Brussels sprouts', 'Brassica oleracea var. gemmifera', 'vegetable', '🥬'],
  ['Kohlrabi', 'Brassica oleracea var. gongylodes', 'vegetable', '🥬'],
  ['Collard greens', 'Brassica oleracea var. viridis', 'vegetable', '🥬'],
  ['Bok choy', 'Brassica rapa subsp. chinensis', 'vegetable', '🥬'],
  ['Napa cabbage', 'Brassica rapa subsp. pekinensis', 'vegetable', '🥬'],
  ['Green beans', 'Phaseolus vulgaris', 'vegetable', '🫛'],
  ['Pole bean', 'Phaseolus vulgaris "Kentucky Wonder"', 'vegetable', '🫛'],
  ['Bush bean', 'Phaseolus vulgaris "Provider"', 'vegetable', '🫛'],
  ['Pea', 'Pisum sativum', 'vegetable', '🫛'],
  ['Snap pea', 'Pisum sativum var. macrocarpon', 'vegetable', '🫛'],
  ['Snow pea', 'Pisum sativum "Oregon Sugar Pod"', 'vegetable', '🫛'],
  ['Edamame', 'Glycine max', 'vegetable', '🫛'],
  ['Fava bean', 'Vicia faba', 'vegetable', '🫛'],
  ['Lima bean', 'Phaseolus lunatus', 'vegetable', '🫛'],
  ['Radish', 'Raphanus sativus', 'vegetable'],
  ['Daikon radish', 'Raphanus sativus var. longipinnatus', 'vegetable'],
  ['Carrot', 'Daucus carota', 'vegetable', '🥕'],
  ['Beet', 'Beta vulgaris subsp. vulgaris', 'vegetable'],
  ['Turnip', 'Brassica rapa subsp. rapa', 'vegetable'],
  ['Parsnip', 'Pastinaca sativa', 'vegetable', '🥕'],
  ['Rutabaga', 'Brassica napus subsp. rapifera', 'vegetable'],
  ['Sweet potato', 'Ipomoea batatas', 'vegetable', '🍠'],
  ['Potato', 'Solanum tuberosum', 'vegetable', '🥔'],
  ['Onion', 'Allium cepa', 'vegetable', '🧅'],
  ['Garlic', 'Allium sativum', 'vegetable', '🧄'],
  ['Shallot', 'Allium cepa var. aggregatum', 'vegetable', '🧅'],
  ['Leek', 'Allium ampeloprasum', 'vegetable'],
  ['Green onion', 'Allium fistulosum', 'vegetable'],
  ['Zucchini', 'Cucurbita pepo', 'vegetable'],
  ['Butternut squash', 'Cucurbita moschata', 'vegetable', '🎃'],
  ['Acorn squash', 'Cucurbita pepo var. turbinata', 'vegetable', '🎃'],
  ['Spaghetti squash', 'Cucurbita pepo "Spaghetti"', 'vegetable', '🎃'],
  ['Delicata squash', 'Cucurbita pepo "Delicata"', 'vegetable', '🎃'],
  ['Pumpkin', 'Cucurbita maxima', 'vegetable', '🎃'],
  ['Watermelon', 'Citrullus lanatus', 'vegetable', '🍉'],
  ['Cantaloupe', 'Cucumis melo var. cantalupensis', 'vegetable', '🍈'],
  ['Honeydew', 'Cucumis melo var. inodorus', 'vegetable', '🍈'],
  ['Sweet corn', 'Zea mays', 'vegetable', '🌽'],
  ['Okra', 'Abelmoschus esculentus', 'vegetable'],
  ['Celery', 'Apium graveolens', 'vegetable'],
  ['Celeriac', 'Apium graveolens var. rapaceum', 'vegetable'],
  ['Asparagus', 'Asparagus officinalis', 'vegetable'],
  ['Artichoke', 'Cynara cardunculus var. scolymus', 'vegetable'],
  ['Rhubarb', 'Rheum rhabarbarum', 'vegetable'],
  ['Tomatillo', 'Physalis philadelphica', 'vegetable'],
  ['Ground cherry', 'Physalis pruinosa', 'vegetable'],
  ['Eggplant', 'Solanum melongena', 'vegetable', '🍆'],
  ['Japanese eggplant', 'Solanum melongena "Ichiban"', 'vegetable', '🍆'],
  ['Florence fennel', 'Foeniculum vulgare var. azoricum', 'vegetable'],
  ['Horseradish', 'Armoracia rusticana', 'vegetable'],
  ['Luffa', 'Luffa aegyptiaca', 'vegetable'],
  ['Bitter melon', 'Momordica charantia', 'vegetable'],
  ['Chayote', 'Sechium edule', 'vegetable'],
  ['Purslane', 'Portulaca oleracea', 'vegetable', '🥬'],
  ['Sunchoke', 'Helianthus tuberosus', 'vegetable'],

  // ═══════════════ FRUIT ═══════════════
  ['Strawberry', 'Fragaria × ananassa', 'flowering', '🍓'],
  ['Alpine strawberry', 'Fragaria vesca', 'flowering', '🍓'],
  ['Blueberry', 'Vaccinium corymbosum', 'flowering', '🫐'],
  ['Cranberry', 'Vaccinium macrocarpon', 'shrub', '🫐'],
  ['Apple', 'Malus domestica', 'tree', '🍎'],
  ['Pear', 'Pyrus communis', 'tree', '🍐'],
  ['Asian pear', 'Pyrus pyrifolia', 'tree', '🍐'],
  ['Peach', 'Prunus persica', 'tree', '🍑'],
  ['Nectarine', 'Prunus persica var. nucipersica', 'tree', '🍑'],
  ['Apricot', 'Prunus armeniaca', 'tree', '🍑'],
  ['Plum', 'Prunus domestica', 'tree'],
  ['Sweet cherry', 'Prunus avium', 'tree', '🍒'],
  ['Sour cherry', 'Prunus cerasus', 'tree', '🍒'],
  ['Fig', 'Ficus carica', 'tree'],
  ['Pomegranate', 'Punica granatum', 'tree'],
  ['Persimmon', 'Diospyros kaki', 'tree'],
  ['Mulberry', 'Morus alba', 'tree'],
  ['Raspberry', 'Rubus idaeus', 'shrub', '🍓'],
  ['Blackberry', 'Rubus fruticosus', 'shrub'],
  ['Gooseberry', 'Ribes uva-crispa', 'shrub'],
  ['Red currant', 'Ribes rubrum', 'shrub'],
  ['Black currant', 'Ribes nigrum', 'shrub'],
  ['Elderberry', 'Sambucus canadensis', 'shrub'],
  ['Grape', 'Vitis vinifera', 'vine', '🍇'],
  ['Kiwi', 'Actinidia deliciosa', 'vine', '🥝'],
  ['Hardy kiwi', 'Actinidia arguta', 'vine', '🥝'],
  ['Pineapple', 'Ananas comosus', 'tropical', '🍍'],
  ['Mango', 'Mangifera indica', 'tree', '🥭'],
  ['Papaya', 'Carica papaya', 'tree'],
  ['Guava', 'Psidium guajava', 'tree'],
  ['Passionfruit', 'Passiflora edulis', 'vine', '🌸'],
  ['Dragon fruit', 'Selenicereus undatus', 'cactus', '🌵'],
  ['Loquat', 'Eriobotrya japonica', 'tree'],
  ['Almond', 'Prunus amygdalus', 'tree'],
  ['Walnut', 'Juglans regia', 'tree'],
  ['Pecan', 'Carya illinoinensis', 'tree'],
  ['Hazelnut', 'Corylus avellana', 'shrub'],
  ['Quince', 'Cydonia oblonga', 'tree'],
  ['Jujube', 'Ziziphus jujuba', 'tree'],
  ['Serviceberry', 'Amelanchier canadensis', 'tree'],
  ['Goji berry', 'Lycium barbarum', 'shrub'],
  ['Honeyberry', 'Lonicera caerulea', 'shrub'],
  ['Orange', 'Citrus sinensis', 'tree', '🍊'],
  ['Mandarin orange', 'Citrus reticulata', 'tree', '🍊'],
  ['Blood orange', 'Citrus sinensis "Moro"', 'tree', '🍊'],
  ['Grapefruit', 'Citrus × paradisi', 'tree'],

  // ═══════════════ ANNUAL FLOWERS ═══════════════
  ['Geranium', 'Pelargonium × hortorum', 'flowering', '🌸'],
  ['Ivy geranium', 'Pelargonium peltatum', 'flowering', '🌸'],
  ['Gerbera daisy', 'Gerbera jamesonii', 'flowering', '🌼'],
  ['Chrysanthemum', 'Chrysanthemum morifolium', 'flowering', '🌼'],
  ['Cyclamen', 'Cyclamen persicum', 'flowering', '🌸'],
  ['Kalanchoe', 'Kalanchoe blossfeldiana "Calandiva"', 'flowering', '🌸'],
  ['Poinsettia', 'Euphorbia pulcherrima', 'flowering', '🌺'],
  ['Marigold', 'Tagetes erecta', 'flowering', '🌼'],
  ['French marigold', 'Tagetes patula', 'flowering', '🌼'],
  ['Petunia', 'Petunia × atkinsiana', 'flowering', '🌸'],
  ['Million bells', 'Calibrachoa × hybrida', 'flowering', '🌸'],
  ['Sunflower', 'Helianthus annuus', 'flowering', '🌻'],
  ['Teddy Bear sunflower', 'Helianthus annuus "Teddy Bear"', 'flowering', '🌻'],
  ['Mammoth sunflower', 'Helianthus annuus "Mammoth"', 'flowering', '🌻'],
  ['Mexican sunflower', 'Tithonia rotundifolia', 'flowering', '🌻'],
  ['Zinnia', 'Zinnia elegans', 'flowering', '🌸'],
  ['Pansy', 'Viola × wittrockiana', 'flowering', '🌸'],
  ['Viola', 'Viola cornuta', 'flowering', '🌸'],
  ['Impatiens', 'Impatiens walleriana', 'flowering', '🌸'],
  ['New Guinea impatiens', 'Impatiens hawkeri', 'flowering', '🌸'],
  ['Fuchsia', 'Fuchsia × hybrida', 'flowering', '🌸'],
  ['Lantana', 'Lantana camara', 'flowering', '🌸'],
  ['Snapdragon', 'Antirrhinum majus', 'flowering', '🌸'],
  ['Cosmos', 'Cosmos bipinnatus', 'flowering', '🌸'],
  ['Nasturtium', 'Tropaeolum majus', 'flowering', '🌸'],
  ['Sweet pea', 'Lathyrus odoratus', 'flowering', '🌸'],
  ['Calendula', 'Calendula officinalis', 'flowering', '🌼'],
  ['Celosia', 'Celosia argentea', 'flowering', '🌸'],
  ['Cockscomb', 'Celosia argentea var. cristata', 'flowering', '🌸'],
  ['Cleome', 'Cleome hassleriana', 'flowering', '🌸'],
  ['Stock', 'Matthiola incana', 'flowering', '🌸'],
  ['Bachelor’s button', 'Centaurea cyanus', 'flowering', '💙'],
  ['Larkspur', 'Consolida ajacis', 'flowering', '💜'],
  ['Love-in-a-mist', 'Nigella damascena', 'flowering', '💙'],
  ['Verbena', 'Verbena × hybrida', 'flowering', '🌸'],
  ['Lobelia', 'Lobelia erinus', 'flowering', '💙'],
  ['Sweet alyssum', 'Lobularia maritima', 'flowering', '🌸'],
  ['Moss rose', 'Portulaca grandiflora', 'flowering', '🌸'],
  ['Gazania', 'Gazania rigens', 'flowering', '🌼'],
  ['Strawflower', 'Xerochrysum bracteatum', 'flowering', '🌼'],
  ['Statice', 'Limonium sinuatum', 'flowering', '💜'],
  ['Globe amaranth', 'Gomphrena globosa', 'flowering', '🌸'],
  ['Ageratum', 'Ageratum houstonianum', 'flowering', '💙'],
  ['Scarlet sage', 'Salvia splendens', 'flowering', '🌺'],
  ['Madagascar periwinkle', 'Catharanthus roseus', 'flowering', '🌸'],
  ['Dusty miller', 'Jacobaea maritima', 'flowering'],
  ['Ornamental kale', 'Brassica oleracea var. acephala', 'flowering', '🥬'],
  ['California poppy', 'Eschscholzia californica', 'flowering', '🌼'],
  ['Iceland poppy', 'Papaver nudicaule', 'flowering', '🌼'],
  ['Shirley poppy', 'Papaver rhoeas', 'flowering', '🌺'],
  ['Moonflower', 'Ipomoea alba', 'flowering', '🌸'],
  ['Four o’clock', 'Mirabilis jalapa', 'flowering', '🌸'],
  ['Browallia', 'Browallia speciosa', 'flowering', '💜'],
  ['Wishbone flower', 'Torenia fournieri', 'flowering', '💜'],
  ['Nemesia', 'Nemesia strumosa', 'flowering', '🌸'],
  ['Diascia', 'Diascia barberae', 'flowering', '🌸'],
  ['Pincushion flower', 'Scabiosa atropurpurea', 'flowering', '💜'],
  ['Angelonia', 'Angelonia angustifolia', 'flowering', '💜'],
  ['Bacopa', 'Chaenostoma cordatum', 'flowering', '🌸'],
  ['Heliotrope', 'Heliotropium arborescens', 'flowering', '💜'],
  ['Licorice plant', 'Helichrysum petiolare', 'flowering'],
  ['Love-lies-bleeding', 'Amaranthus caudatus', 'flowering', '🌺'],
  ['Canterbury bells', 'Campanula medium', 'flowering', '💜'],
  ['Forget-me-not', 'Myosotis sylvatica', 'flowering', '💙'],
  ['Wallflower', 'Erysimum cheiri', 'flowering', '🌼'],
  ['Flowering tobacco', 'Nicotiana alata', 'flowering', '🌸'],
  ['Sweet William', 'Dianthus barbatus', 'flowering', '🌸'],
  ['Black-eyed Susan vine', 'Thunbergia alata', 'vine', '🌼'],
  ['Cypress vine', 'Ipomoea quamoclit', 'vine', '🌺'],
  ['Scarlet runner bean', 'Phaseolus coccineus', 'vine', '🌺'],
  ['Cup and saucer vine', 'Cobaea scandens', 'vine', '💜'],

  // ═══════════════ PERENNIAL FLOWERS ═══════════════
  ['Purple coneflower', 'Echinacea purpurea', 'flowering', '🌸'],
  ['Black-eyed Susan', 'Rudbeckia hirta', 'flowering', '🌼'],
  ['Coreopsis', 'Coreopsis grandiflora', 'flowering', '🌼'],
  ['Daylily', 'Hemerocallis spp.', 'flowering', '🌺'],
  ['Stella d’Oro daylily', 'Hemerocallis "Stella de Oro"', 'flowering', '🌼'],
  ['Hosta', 'Hosta spp.', 'flowering', '🌿'],
  ['Hosta Blue Angel', 'Hosta "Blue Angel"', 'flowering', '🌿'],
  ['Hosta Patriot', 'Hosta "Patriot"', 'flowering', '🌿'],
  ['Hosta Sum and Substance', 'Hosta "Sum and Substance"', 'flowering', '🌿'],
  ['Astilbe', 'Astilbe × arendsii', 'flowering', '🌸'],
  ['Coral bells', 'Heuchera sanguinea', 'flowering', '🌿'],
  ['Palace Purple coral bells', 'Heuchera micrantha "Palace Purple"', 'flowering', '🌿'],
  ['Autumn Joy sedum', 'Hylotelephium "Herbstfreude"', 'succulent', '🌸'],
  ['May Night salvia', 'Salvia nemorosa "Mainacht"', 'flowering', '💜'],
  ['Catmint Walker’s Low', 'Nepeta × faassenii "Walker\'s Low"', 'flowering', '💜'],
  ['Yarrow', 'Achillea millefolium', 'flowering', '🌼'],
  ['Bee balm', 'Monarda didyma', 'flowering', '🌺'],
  ['Garden phlox', 'Phlox paniculata', 'flowering', '🌸'],
  ['Creeping phlox', 'Phlox subulata', 'flowering', '🌸'],
  ['Delphinium', 'Delphinium elatum', 'flowering', '💙'],
  ['Foxglove', 'Digitalis purpurea', 'flowering', '💜'],
  ['Hollyhock', 'Alcea rosea', 'flowering', '🌸'],
  ['Lupine', 'Lupinus polyphyllus', 'flowering', '💜'],
  ['Columbine', 'Aquilegia vulgaris', 'flowering', '🌸'],
  ['Bleeding heart', 'Lamprocapnos spectabilis', 'flowering', '🌸'],
  ['Cheddar pink dianthus', 'Dianthus gratianopolitanus', 'flowering', '🌸'],
  ['Shasta daisy', 'Leucanthemum × superbum', 'flowering', '🌼'],
  ['Blanket flower', 'Gaillardia × grandiflora', 'flowering', '🌼'],
  ['Penstemon', 'Penstemon digitalis', 'flowering', '🌸'],
  ['Speedwell', 'Veronica spicata', 'flowering', '💜'],
  ['Bellflower', 'Campanula persicifolia', 'flowering', '💜'],
  ['New England aster', 'Symphyotrichum novae-angliae', 'flowering', '💜'],
  ['Goldenrod', 'Solidago canadensis', 'flowering', '🌼'],
  ['Joe Pye weed', 'Eutrochium purpureum', 'flowering', '🌸'],
  ['Blazing star', 'Liatris spicata', 'flowering', '💜'],
  ['Sneezeweed', 'Helenium autumnale', 'flowering', '🌼'],
  ['Monkshood', 'Aconitum napellus', 'flowering', '💜'],
  ['Lady’s mantle', 'Alchemilla mollis', 'flowering', '🌿'],
  ['Brunnera', 'Brunnera macrophylla', 'flowering', '💙'],
  ['Lungwort', 'Pulmonaria officinalis', 'flowering', '🌸'],
  ['Lenten rose', 'Helleborus orientalis', 'flowering', '🌸'],
  ['Bearded iris', 'Iris germanica', 'flowering', '💜'],
  ['Siberian iris', 'Iris sibirica', 'flowering', '💜'],
  ['Oriental poppy', 'Papaver orientale', 'flowering', '🌺'],
  ['Lamb’s ear', 'Stachys byzantina', 'flowering', '🌿'],
  ['Russian sage', 'Salvia yangii', 'flowering', '💜'],
  ['Gaura', 'Oenothera lindheimeri', 'flowering', '🌸'],
  ['Crocosmia', 'Crocosmia × crocosmiiflora', 'flowering', '🌺'],
  ['Red hot poker', 'Kniphofia uvaria', 'flowering', '🌺'],
  ['Sea holly', 'Eryngium planum', 'flowering', '💙'],
  ['Globe thistle', 'Echinops ritro', 'flowering', '💙'],
  ['Baby’s breath', 'Gypsophila paniculata', 'flowering', '🌸'],
  ['Candytuft', 'Iberis sempervirens', 'flowering', '🌸'],
  ['Bugleweed', 'Ajuga reptans', 'flowering', '💜'],
  ['Sweet woodruff', 'Galium odoratum', 'flowering', '🌿'],
  ['Lily of the valley', 'Convallaria majalis', 'flowering', '🌸'],
  ['Epimedium', 'Epimedium × versicolor', 'flowering', '🌸'],
  ['Foamflower', 'Tiarella cordifolia', 'flowering', '🌸'],
  ['Avens', 'Geum coccineum', 'flowering', '🌺'],
  ['Primrose', 'Primula vulgaris', 'flowering', '🌼'],
  ['Sweet violet', 'Viola odorata', 'flowering', '💜'],
  ['Creeping jenny', 'Lysimachia nummularia', 'flowering', '🌿'],
  ['Dead nettle', 'Lamium maculatum', 'flowering', '🌸'],
  ['Rock cress', 'Aubrieta deltoidea', 'flowering', '💜'],
  ['Basket of gold', 'Aurinia saxatilis', 'flowering', '🌼'],
  ['Snow-in-summer', 'Cerastium tomentosum', 'flowering', '🌸'],
  ['Sea thrift', 'Armeria maritima', 'flowering', '🌸'],
  ['Cranesbill geranium', 'Geranium sanguineum', 'flowering', '🌸'],
  ['Geranium Rozanne', 'Geranium "Rozanne"', 'flowering', '💜'],
  ['Obedient plant', 'Physostegia virginiana', 'flowering', '🌸'],
  ['Turtlehead', 'Chelone glabra', 'flowering', '🌸'],
  ['Cardinal flower', 'Lobelia cardinalis', 'flowering', '🌺'],
  ['Blue star', 'Amsonia tabernaemontana', 'flowering', '💙'],
  ['False indigo', 'Baptisia australis', 'flowering', '💙'],
  ['Goat’s beard', 'Aruncus dioicus', 'flowering', '🌸'],
  ['Meadow rue', 'Thalictrum aquilegiifolium', 'flowering', '💜'],
  ['Toad lily', 'Tricyrtis hirta', 'flowering', '🌸'],
  ['Japanese anemone', 'Anemone × hybrida', 'flowering', '🌸'],
  ['Balloon flower', 'Platycodon grandiflorus', 'flowering', '💙'],
  ['Evening primrose', 'Oenothera biennis', 'flowering', '🌼'],
  ['Peony', 'Paeonia lactiflora', 'flowering', '🌸'],
  ['Rose', 'Rosa spp.', 'flowering', '🌹'],
  ['Hibiscus', 'Hibiscus rosa-sinensis', 'flowering', '🌺'],
  ['Gardenia', 'Gardenia jasminoides', 'flowering', '🌼'],
  ['Dahlia', 'Dahlia pinnata', 'flowering', '🌸'],
  ['Amaryllis', 'Hippeastrum spp.', 'bulb', '🌷'],
  ['Lily', 'Lilium spp.', 'bulb', '🌷'],

  // ═══════════════ BULBS ═══════════════
  ['Tulip', 'Tulipa gesneriana', 'bulb', '🌷'],
  ['Daffodil', 'Narcissus pseudonarcissus', 'bulb', '🌼'],
  ['Paperwhite', 'Narcissus papyraceus', 'bulb', '🌸'],
  ['Hyacinth', 'Hyacinthus orientalis', 'bulb', '🌸'],
  ['Crocus', 'Crocus vernus', 'bulb', '💜'],
  ['Snowdrop', 'Galanthus nivalis', 'bulb', '🌸'],
  ['Giant allium', 'Allium giganteum', 'bulb', '💜'],
  ['Grape hyacinth', 'Muscari armeniacum', 'bulb', '💜'],
  ['Freesia', 'Freesia × hybrida', 'bulb', '🌸'],
  ['Gladiolus', 'Gladiolus × hortulanus', 'bulb', '🌺'],
  ['Canna lily', 'Canna × generalis', 'bulb', '🌺'],
  ['Calla lily', 'Zantedeschia aethiopica', 'bulb', '🌸'],
  ['Ranunculus', 'Ranunculus asiaticus', 'bulb', '🌸'],
  ['Windflower', 'Anemone coronaria', 'bulb', '🌸'],
  ['Stargazer lily', 'Lilium "Stargazer"', 'bulb', '🌷'],
  ['Asiatic lily', 'Lilium "Asiatic hybrids"', 'bulb', '🌷'],
  ['Tiger lily', 'Lilium lancifolium', 'bulb', '🌷'],
  ['Easter lily', 'Lilium longiflorum', 'bulb', '🌷'],
  ['Autumn crocus', 'Colchicum autumnale', 'bulb', '💜'],
  ['Siberian squill', 'Scilla siberica', 'bulb', '💙'],
  ['Crown imperial', 'Fritillaria imperialis', 'bulb', '🌺'],
  ['Camas', 'Camassia quamash', 'bulb', '💙'],
  ['Dutch iris', 'Iris × hollandica', 'bulb', '💜'],
  ['Spanish bluebell', 'Hyacinthoides hispanica', 'bulb', '💙'],
  ['Winter aconite', 'Eranthis hyemalis', 'bulb', '🌼'],

  // ═══════════════ SHRUBS ═══════════════
  ['Azalea', 'Rhododendron simsii', 'shrub', '🌸'],
  ['Rhododendron', 'Rhododendron spp.', 'shrub', '🌸'],
  ['Camellia', 'Camellia japonica', 'shrub', '🌸'],
  ['Bigleaf hydrangea', 'Hydrangea macrophylla', 'shrub', '🌸'],
  ['Limelight hydrangea', 'Hydrangea paniculata "Limelight"', 'shrub', '🌸'],
  ['Oakleaf hydrangea', 'Hydrangea quercifolia', 'shrub', '🌸'],
  ['Annabelle hydrangea', 'Hydrangea arborescens "Annabelle"', 'shrub', '🌸'],
  ['Lilac', 'Syringa vulgaris', 'shrub', '💜'],
  ['Dwarf Korean lilac', 'Syringa meyeri "Palibin"', 'shrub', '💜'],
  ['Forsythia', 'Forsythia × intermedia', 'shrub', '🌼'],
  ['Knock Out rose', 'Rosa "Knock Out"', 'shrub', '🌹'],
  ['Climbing rose', 'Rosa "New Dawn"', 'vine', '🌹'],
  ['English rose', 'Rosa "Graham Thomas"', 'shrub', '🌹'],
  ['Boxwood', 'Buxus sempervirens', 'shrub'],
  ['English holly', 'Ilex aquifolium', 'shrub'],
  ['Winterberry', 'Ilex verticillata', 'shrub'],
  ['Inkberry holly', 'Ilex glabra', 'shrub'],
  ['Privet', 'Ligustrum vulgare', 'shrub'],
  ['Snowball viburnum', 'Viburnum opulus "Roseum"', 'shrub', '🌸'],
  ['Arrowwood viburnum', 'Viburnum dentatum', 'shrub'],
  ['Koreanspice viburnum', 'Viburnum carlesii', 'shrub', '🌸'],
  ['Spirea', 'Spiraea japonica', 'shrub', '🌸'],
  ['Bridal wreath spirea', 'Spiraea prunifolia', 'shrub', '🌸'],
  ['Weigela', 'Weigela florida', 'shrub', '🌸'],
  ['Mock orange', 'Philadelphus coronarius', 'shrub', '🌸'],
  ['Ninebark', 'Physocarpus opulifolius', 'shrub'],
  ['Smoke bush', 'Cotinus coggygria', 'shrub'],
  ['Butterfly bush', 'Buddleja davidii', 'shrub', '💜'],
  ['Rose of Sharon', 'Hibiscus syriacus', 'shrub', '🌸'],
  ['Crape myrtle', 'Lagerstroemia indica', 'shrub', '🌸'],
  ['Abelia', 'Abelia × grandiflora', 'shrub', '🌸'],
  ['Japanese barberry', 'Berberis thunbergii', 'shrub'],
  ['Burning bush', 'Euonymus alatus', 'shrub'],
  ['Potentilla', 'Potentilla fruticosa', 'shrub', '🌼'],
  ['Flowering quince', 'Chaenomeles speciosa', 'shrub', '🌺'],
  ['Deutzia', 'Deutzia gracilis', 'shrub', '🌸'],
  ['Beautyberry', 'Callicarpa americana', 'shrub', '💜'],
  ['Bottlebrush', 'Callistemon citrinus', 'shrub', '🌺'],
  ['Oleander', 'Nerium oleander', 'shrub', '🌸'],
  ['Hardy hibiscus', 'Hibiscus moscheutos', 'shrub', '🌺'],
  ['Juniper', 'Juniperus chinensis', 'shrub', '🌲'],
  ['Yew', 'Taxus baccata', 'shrub', '🌲'],
  ['Arborvitae', 'Thuja occidentalis', 'shrub', '🌲'],
  ['Green Giant arborvitae', 'Thuja "Green Giant"', 'tree', '🌲'],
  ['Cotoneaster', 'Cotoneaster horizontalis', 'shrub'],
  ['Firethorn', 'Pyracantha coccinea', 'shrub'],
  ['Oregon grape', 'Mahonia aquifolium', 'shrub'],
  ['Heavenly bamboo', 'Nandina domestica', 'shrub'],
  ['Japanese pieris', 'Pieris japonica', 'shrub', '🌸'],
  ['Daphne', 'Daphne odora', 'shrub', '🌸'],
  ['Witch hazel', 'Hamamelis virginiana', 'shrub', '🌼'],
  ['Staghorn sumac', 'Rhus typhina', 'shrub'],
  ['Fothergilla', 'Fothergilla gardenii', 'shrub'],
  ['Virginia sweetspire', 'Itea virginica', 'shrub'],
  ['Red twig dogwood', 'Cornus sericea', 'shrub'],
  ['Bluebeard', 'Caryopteris × clandonensis', 'shrub', '💙'],
  ['St. John’s wort', 'Hypericum calycinum', 'shrub', '🌼'],
  ['Heather', 'Calluna vulgaris', 'shrub', '💜'],
  ['Chokeberry', 'Aronia melanocarpa', 'shrub'],
  ['Gardenia Frostproof', 'Gardenia jasminoides "Frostproof"', 'shrub', '🌼'],

  // ═══════════════ OUTDOOR TREES ═══════════════
  ['Japanese maple', 'Acer palmatum', 'tree', '🍁'],
  ['Bloodgood Japanese maple', 'Acer palmatum "Bloodgood"', 'tree', '🍁'],
  ['Red maple', 'Acer rubrum', 'tree', '🍁'],
  ['Sugar maple', 'Acer saccharum', 'tree', '🍁'],
  ['River birch', 'Betula nigra', 'tree'],
  ['Paper birch', 'Betula papyrifera', 'tree'],
  ['White oak', 'Quercus alba', 'tree'],
  ['Red oak', 'Quercus rubra', 'tree'],
  ['Live oak', 'Quercus virginiana', 'tree'],
  ['Southern magnolia', 'Magnolia grandiflora', 'tree', '🌸'],
  ['Saucer magnolia', 'Magnolia × soulangeana', 'tree', '🌸'],
  ['Star magnolia', 'Magnolia stellata', 'tree', '🌸'],
  ['Kwanzan cherry', 'Prunus serrulata "Kanzan"', 'tree', '🌸'],
  ['Yoshino cherry', 'Prunus × yedoensis', 'tree', '🌸'],
  ['Flowering crabapple', 'Malus "Prairifire"', 'tree', '🌸'],
  ['Eastern redbud', 'Cercis canadensis', 'tree', '🌸'],
  ['Flowering dogwood', 'Cornus florida', 'tree', '🌸'],
  ['Kousa dogwood', 'Cornus kousa', 'tree', '🌸'],
  ['Ginkgo', 'Ginkgo biloba', 'tree'],
  ['Honey locust', 'Gleditsia triacanthos', 'tree'],
  ['Tulip tree', 'Liriodendron tulipifera', 'tree'],
  ['Sweetgum', 'Liquidambar styraciflua', 'tree'],
  ['Littleleaf linden', 'Tilia cordata', 'tree'],
  ['American hornbeam', 'Carpinus caroliniana', 'tree'],
  ['Katsura', 'Cercidiphyllum japonicum', 'tree'],
  ['Japanese zelkova', 'Zelkova serrata', 'tree'],
  ['Colorado blue spruce', 'Picea pungens', 'tree', '🌲'],
  ['Norway spruce', 'Picea abies', 'tree', '🌲'],
  ['Eastern white pine', 'Pinus strobus', 'tree', '🌲'],
  ['Mugo pine', 'Pinus mugo', 'shrub', '🌲'],
  ['Bald cypress', 'Taxodium distichum', 'tree', '🌲'],
  ['Dawn redwood', 'Metasequoia glyptostroboides', 'tree', '🌲'],
  ['Italian cypress', 'Cupressus sempervirens', 'tree', '🌲'],
  ['Weeping willow', 'Salix babylonica', 'tree'],
  ['Hawthorn', 'Crataegus laevigata', 'tree', '🌸'],
  ['Golden chain tree', 'Laburnum × watereri', 'tree', '🌼'],
  ['Sourwood', 'Oxydendrum arboreum', 'tree'],
  ['Japanese stewartia', 'Stewartia pseudocamellia', 'tree', '🌸'],

  // ═══════════════ OUTDOOR VINES & CLIMBERS ═══════════════
  ['Wisteria', 'Wisteria sinensis', 'vine', '💜'],
  ['Trumpet vine', 'Campsis radicans', 'vine', '🌺'],
  ['Coral honeysuckle', 'Lonicera sempervirens', 'vine', '🌺'],
  ['Goldflame honeysuckle', 'Lonicera × heckrottii', 'vine', '🌸'],
  ['Climbing hydrangea', 'Hydrangea anomala subsp. petiolaris', 'vine', '🌸'],
  ['Virginia creeper', 'Parthenocissus quinquefolia', 'vine', '🍃'],
  ['Boston ivy', 'Parthenocissus tricuspidata', 'vine', '🍃'],
  ['Star jasmine', 'Trachelospermum jasminoides', 'vine', '🌸'],
  ['Carolina jessamine', 'Gelsemium sempervirens', 'vine', '🌼'],
  ['Chocolate vine', 'Akebia quinata', 'vine', '💜'],
  ['Hops', 'Humulus lupulus', 'vine', '🍃'],
  ['Sweet autumn clematis', 'Clematis terniflora', 'vine', '🌸'],
  ['Dutchman’s pipe', 'Aristolochia macrophylla', 'vine', '🍃'],
  ['Crossvine', 'Bignonia capreolata', 'vine', '🌺'],

  // ═══════════════ GRASSES & BAMBOO ═══════════════
  ['Lucky bamboo grove', 'Dracaena braunii', 'grass', '🎋'],
  ['Golden bamboo', 'Phyllostachys aurea', 'grass', '🎋'],
  ['Black bamboo', 'Phyllostachys nigra', 'grass', '🎋'],
  ['Fountain grass', 'Pennisetum setaceum', 'grass'],
  ['Purple fountain grass', 'Pennisetum setaceum "Rubrum"', 'grass'],
  ['Papyrus', 'Cyperus papyrus', 'grass'],
  ['Umbrella sedge', 'Cyperus alternifolius', 'grass'],
  ['Mondo grass', 'Ophiopogon japonicus', 'grass'],
  ['Black mondo grass', 'Ophiopogon planiscapus "Nigrescens"', 'grass'],
  ['Blue fescue', 'Festuca glauca', 'grass'],
  ['Maiden grass', 'Miscanthus sinensis "Gracillimus"', 'grass'],
  ['Zebra grass', 'Miscanthus sinensis "Zebrinus"', 'grass'],
  ['Karl Foerster grass', 'Calamagrostis × acutiflora "Karl Foerster"', 'grass'],
  ['Switchgrass', 'Panicum virgatum', 'grass'],
  ['Little bluestem', 'Schizachyrium scoparium', 'grass'],
  ['Big bluestem', 'Andropogon gerardii', 'grass'],
  ['Pink muhly grass', 'Muhlenbergia capillaris', 'grass', '🌸'],
  ['Japanese forest grass', 'Hakonechloa macra', 'grass'],
  ['Blue oat grass', 'Helictotrichon sempervirens', 'grass'],
  ['Pampas grass', 'Cortaderia selloana', 'grass'],
  ['Japanese sedge', 'Carex oshimensis "Evergold"', 'grass'],
  ['Liriope', 'Liriope muscari', 'grass', '💜'],
  ['Sweet flag', 'Acorus gramineus', 'grass'],
  ['Mexican feather grass', 'Nassella tenuissima', 'grass'],
  ['Prairie dropseed', 'Sporobolus heterolepis', 'grass'],
  ['Tufted hair grass', 'Deschampsia cespitosa', 'grass'],

  // ═══════════════ ORCHIDS ═══════════════
  ['Moth orchid', 'Phalaenopsis amabilis', 'orchid', '🌸'],
  ['Dendrobium orchid', 'Dendrobium nobile', 'orchid', '🌸'],
  ['Cattleya orchid', 'Cattleya labiata', 'orchid', '🌸'],
  ['Oncidium orchid', 'Oncidium altissimum', 'orchid', '🌸'],
  ['Cymbidium orchid', 'Cymbidium spp.', 'orchid', '🌸'],
  ['Lady slipper orchid', 'Paphiopedilum spp.', 'orchid', '🌸'],
  ['Vanda orchid', 'Vanda coerulea', 'orchid', '🌸'],
  ['Jewel orchid', 'Ludisia discolor', 'orchid'],
  ['Pansy orchid', 'Miltoniopsis spp.', 'orchid', '🌸'],
  ['Spider orchid', 'Brassia spp.', 'orchid', '🌸'],
  ['Zygopetalum orchid', 'Zygopetalum spp.', 'orchid', '💜'],
  ['Reed orchid', 'Epidendrum radicans', 'orchid', '🌺'],
  ['Ground orchid', 'Spathoglottis plicata', 'orchid', '💜'],
  ['Hardy orchid', 'Bletilla striata', 'orchid', '🌸'],

  // ═══════════════ CARNIVOROUS ═══════════════
  ['Venus flytrap', 'Dionaea muscipula', 'carnivorous', '🪰'],
  ['Pitcher plant', 'Sarracenia purpurea', 'carnivorous', '🪰'],
  ['Sundew', 'Drosera capensis', 'carnivorous', '🪰'],
  ['Spoonleaf sundew', 'Drosera spatulata', 'carnivorous', '🪰'],
  ['Tropical pitcher', 'Nepenthes spp.', 'carnivorous', '🪰'],
  ['Butterwort', 'Pinguicula spp.', 'carnivorous', '🪰'],
  ['Cobra lily', 'Darlingtonia californica', 'carnivorous', '🪰'],
  ['Australian pitcher plant', 'Cephalotus follicularis', 'carnivorous', '🪰'],

  // ═══════════════ MORE HOUSEPLANT FAVORITES ═══════════════
  ['Snow Queen pothos', 'Epipremnum aureum "Snow Queen"', 'vine', '🍃'],
  ['Philodendron Lemon Lime', 'Philodendron hederaceum "Lemon Lime"', 'vine', '🍃'],
  ['Philodendron Burle Marx', 'Philodendron burle-marxii', 'tropical'],
  ['Philodendron Camposportoanum', 'Philodendron camposportoanum', 'vine', '🍃'],
  ['Philodendron Painted Lady', 'Philodendron "Painted Lady"', 'tropical'],
  ['Philodendron Florida Green', 'Philodendron "Florida Green"', 'vine', '🍃'],
  ['Philodendron Florida Ghost', 'Philodendron "Florida Ghost"', 'vine', '🍃'],
  ['Philodendron Jose Buono', 'Philodendron "Jose Buono"', 'tropical'],
  ['Philodendron Tortum', 'Philodendron tortum', 'tropical'],
  ['Philodendron Splendid', 'Philodendron "Splendid"', 'tropical'],
  ['Philodendron Silver Stripe', 'Philodendron hederaceum "Silver Stripe"', 'vine', '🍃'],
  ['Monstera Peru', 'Monstera karstenianum', 'vine', '🍃'],
  ['Monstera Esqueleto', 'Monstera epipremnoides', 'tropical'],
  ['Alocasia Bambino', 'Alocasia × amazonica "Bambino"', 'tropical'],
  ['Alocasia Sarian', 'Alocasia "Sarian"', 'tropical'],
  ['Alocasia Wentii', 'Alocasia wentii', 'tropical'],
  ['Alocasia Pink Dragon', 'Alocasia "Pink Dragon"', 'tropical'],
  ['Alocasia Cucullata', 'Alocasia cucullata', 'tropical'],
  ['Alocasia Portodora', 'Alocasia portodora', 'tropical'],
  ['Anthurium Hookeri', 'Anthurium hookeri', 'tropical'],
  ['Anthurium Magnificum', 'Anthurium magnificum', 'tropical'],
  ['Aglaonema Sparkling Sarah', 'Aglaonema "Sparkling Sarah"', 'tropical'],
  ['Syngonium Milk Confetti', 'Syngonium podophyllum "Milk Confetti"', 'vine', '🍃'],
  ['Syngonium Berry Allusion', 'Syngonium podophyllum "Berry Allusion"', 'vine', '🍃'],
  ['Calathea Beauty Star', 'Goeppertia ornata "Beauty Star"', 'tropical', '🪴'],
  ['Calathea Vittata', 'Goeppertia elliptica "Vittata"', 'tropical', '🪴'],
  ['Maranta Silver Band', 'Maranta leuconeura "Silver Band"', 'tropical', '🪴'],
  ['Stromanthe Magic Star', 'Stromanthe sanguinea "Magic Star"', 'tropical'],
  ['Ctenanthe Amagris', 'Ctenanthe burle-marxii "Amagris"', 'tropical'],
  ['Peperomia Ginny', 'Peperomia clusiifolia "Ginny"', 'tropical'],
  ['Peperomia Piccolo Banda', 'Peperomia albovittata "Piccolo Banda"', 'tropical'],
  ['Peperomia Pixie Lime', 'Peperomia orba "Pixie Lime"', 'tropical'],
  ['Cupid peperomia', 'Peperomia serpens "Variegata"', 'vine', '🍃'],
  ['Pilea Moon Valley', 'Pilea mollis "Moon Valley"', 'tropical'],
  ['Pilea Norfolk', 'Pilea spruceana "Norfolk"', 'tropical'],
  ['Fittonia Red Anne', 'Fittonia albivenis "Red Anne"', 'tropical'],
  ['Strawberry begonia', 'Saxifraga stolonifera', 'tropical'],
  ['Callisia Pink Lady', 'Callisia repens "Pink Lady"', 'vine', '🍃'],
  ['Iron cross oxalis', 'Oxalis tetraphylla "Iron Cross"', 'tropical'],
  ['Shamrock plant', 'Oxalis regnellii', 'tropical'],
  ['Schefflera Amate', 'Schefflera actinophylla "Amate"', 'tree'],
  ['Dracaena Colorama', 'Dracaena marginata "Colorama"', 'tree'],
  ['Dracaena Tarzan', 'Dracaena marginata "Tarzan"', 'tree'],
  ['ZZ Zenzi', 'Zamioculcas zamiifolia "Zenzi"', 'tropical'],
  ['Homalomena Emerald Gem', 'Homalomena rubescens "Emerald Gem"', 'tropical'],
  ['Ficus Ginseng', 'Ficus microcarpa "Ginseng"', 'tree', '🌳'],
  ['Ficus Moclame', 'Ficus microcarpa "Moclame"', 'tree', '🌳'],
  ['Oak leaf ivy', 'Cissus rhombifolia "Ellen Danica"', 'vine', '🍃'],
  ['Cissus Amazonica', 'Cissus amazonica', 'vine', '🍃'],
  ['Angel wings senecio', 'Senecio candicans "Angel Wings"', 'tropical'],
  ['Aeschynanthus Twister', 'Aeschynanthus radicans "Twister"', 'vine', '🌸'],
  ['Columnea', 'Columnea gloriosa', 'vine', '🌸'],
  ['Streptocarpella', 'Streptocarpus saxorum', 'flowering', '💜'],
  ['Persian shield', 'Strobilanthes dyeriana', 'tropical', '💜'],
  ['Bloodleaf', 'Iresine herbstii', 'tropical'],
  ['Copperleaf', 'Acalypha wilkesiana', 'tropical'],
  ['Chenille plant', 'Acalypha hispida', 'tropical', '🌺'],
  ['Clivia', 'Clivia miniata', 'tropical', '🌺'],
  ['Plumeria', 'Plumeria rubra', 'tree', '🌸'],
  ['Shrimp plant', 'Justicia brandegeeana', 'flowering', '🌸'],
  ['Firecracker plant', 'Russelia equisetiformis', 'flowering', '🌺'],
  ['Cigar plant', 'Cuphea ignea', 'flowering', '🌺'],
  ['Mexican heather', 'Cuphea hyssopifolia', 'flowering', '💜'],
  ['Cat whiskers', 'Orthosiphon aristatus', 'flowering', '🌸'],
  ['Blue daze', 'Evolvulus glomeratus', 'flowering', '💙'],
  ['Fan flower', 'Scaevola aemula', 'flowering', '💜'],

  // ═══════════════ MORE SUCCULENTS & CACTI ═══════════════
  ['Baby burro’s tail', 'Sedum burrito', 'succulent'],
  ['Buddha’s temple crassula', 'Crassula "Buddha\'s Temple"', 'succulent'],
  ['Crassula Springtime', 'Crassula "Springtime"', 'succulent'],
  ['Watch chain crassula', 'Crassula muscosa', 'succulent'],
  ['Lavender scallops', 'Kalanchoe fedtschenkoi', 'succulent'],
  ['Kalanchoe Pink Butterflies', 'Kalanchoe "Pink Butterflies"', 'succulent'],
  ['Golden Hahnii snake plant', 'Dracaena trifasciata "Golden Hahnii"', 'succulent', '🌵'],
  ['Starfish snake plant', 'Dracaena cylindrica "Boncel"', 'succulent', '🌵'],
  ['Gasteria Little Warty', 'Gasteria "Little Warty"', 'succulent'],
  ['Haworthia Retusa', 'Haworthia retusa', 'succulent'],
  ['Echeveria Neon Breakers', 'Echeveria "Neon Breakers"', 'succulent'],
  ['Echeveria Dusty Rose', 'Echeveria "Dusty Rose"', 'succulent'],
  ['Graptosedum California Sunset', '× Graptosedum "California Sunset"', 'succulent'],
  ['Graptopetalum Superbum', 'Graptopetalum superbum', 'succulent'],
  ['Aloe Blue Elf', 'Aloe "Blue Elf"', 'succulent'],
  ['Candelabra tree', 'Euphorbia ingens', 'succulent'],
  ['Firesticks', 'Euphorbia tirucalli "Sticks on Fire"', 'succulent'],
  ['String of fish hooks', 'Curio radicans "Fish Hooks"', 'vine', '🍃'],
  ['String of needles', 'Ceropegia linearis', 'vine', '🍃'],
  ['Watermelon dischidia', 'Dischidia ovata', 'vine', '🍃'],
  ['Silver dollar vine', 'Xerosicyos danguyi', 'vine', '🍃'],
  ['Silver squill', 'Ledebouria socialis', 'succulent'],
  ['Angel wings cactus', 'Opuntia microdasys var. albispina', 'cactus', '🌵'],
  ['Rainbow hedgehog cactus', 'Echinocereus rigidissimus', 'cactus', '🌵'],
  ['Peanut cactus', 'Chamaecereus silvestrii', 'cactus', '🌵'],
  ['Brain cactus', 'Stenocactus multicostatus', 'cactus', '🌵'],
  ['Eve’s needle cactus', 'Austrocylindropuntia subulata', 'cactus', '🌵'],
  ['Red mistletoe cactus', 'Rhipsalis ramulosa', 'cactus', '🌵'],
  ['Lepismium', 'Lepismium bolivianum', 'cactus', '🌵'],

  // ═══════════════ GARDEN-CENTER CLASSICS (named varieties) ═══════════════
  ['Coneflower Cheyenne Spirit', 'Echinacea "Cheyenne Spirit"', 'flowering', '🌸'],
  ['Coneflower White Swan', 'Echinacea purpurea "White Swan"', 'flowering', '🌸'],
  ['Rudbeckia Goldsturm', 'Rudbeckia fulgida "Goldsturm"', 'flowering', '🌼'],
  ['Shasta daisy Becky', 'Leucanthemum × superbum "Becky"', 'flowering', '🌼'],
  ['Coreopsis Moonbeam', 'Coreopsis verticillata "Moonbeam"', 'flowering', '🌼'],
  ['Phlox David', 'Phlox paniculata "David"', 'flowering', '🌸'],
  ['Astilbe Fanal', 'Astilbe × arendsii "Fanal"', 'flowering', '🌺'],
  ['Hosta Halcyon', 'Hosta "Halcyon"', 'flowering', '🌿'],
  ['Hosta Guacamole', 'Hosta "Guacamole"', 'flowering', '🌿'],
  ['Hosta Francee', 'Hosta "Francee"', 'flowering', '🌿'],
  ['Heuchera Caramel', 'Heuchera "Caramel"', 'flowering', '🌿'],
  ['Heuchera Obsidian', 'Heuchera "Obsidian"', 'flowering', '🌿'],
  ['Daylily Happy Returns', 'Hemerocallis "Happy Returns"', 'flowering', '🌼'],
  ['Daylily Pardon Me', 'Hemerocallis "Pardon Me"', 'flowering', '🌺'],
  ['Salvia Caradonna', 'Salvia nemorosa "Caradonna"', 'flowering', '💜'],
  ['Lavender Hidcote', 'Lavandula angustifolia "Hidcote"', 'herb', '💜'],
  ['Lavender Munstead', 'Lavandula angustifolia "Munstead"', 'herb', '💜'],
  ['Lavender Phenomenal', 'Lavandula × intermedia "Phenomenal"', 'herb', '💜'],
  ['Sedum Matrona', 'Hylotelephium "Matrona"', 'succulent', '🌸'],
  ['Peony Sarah Bernhardt', 'Paeonia lactiflora "Sarah Bernhardt"', 'flowering', '🌸'],
  ['Peony Karl Rosenfield', 'Paeonia lactiflora "Karl Rosenfield"', 'flowering', '🌺'],
  ['Iris Immortality', 'Iris germanica "Immortality"', 'flowering', '🌸'],
  ['Hydrangea Endless Summer', 'Hydrangea macrophylla "Endless Summer"', 'shrub', '🌸'],
  ['Hydrangea Little Lime', 'Hydrangea paniculata "Little Lime"', 'shrub', '🌸'],
  ['Hydrangea Nikko Blue', 'Hydrangea macrophylla "Nikko Blue"', 'shrub', '💙'],
  ['Hydrangea Pinky Winky', 'Hydrangea paniculata "Pinky Winky"', 'shrub', '🌸'],
  ['Hydrangea Vanilla Strawberry', 'Hydrangea paniculata "Vanilla Strawberry"', 'shrub', '🌸'],
  ['Rose Peace', 'Rosa "Peace"', 'shrub', '🌹'],
  ['Rose Iceberg', 'Rosa "Iceberg"', 'shrub', '🌹'],
  ['Rose Mister Lincoln', 'Rosa "Mister Lincoln"', 'shrub', '🌹'],
  ['Rose Queen Elizabeth', 'Rosa "Queen Elizabeth"', 'shrub', '🌹'],
  ['Rose Double Knock Out', 'Rosa "Double Knock Out"', 'shrub', '🌹'],
  ['Butterfly bush Black Knight', 'Buddleja davidii "Black Knight"', 'shrub', '💜'],
  ['Clematis Nelly Moser', 'Clematis "Nelly Moser"', 'vine', '🌸'],
  ['Dahlia Cafe au Lait', 'Dahlia "Café au Lait"', 'flowering', '🌸'],
  ['Dahlia Bishop of Llandaff', 'Dahlia "Bishop of Llandaff"', 'flowering', '🌺'],
  ['Tulip Queen of Night', 'Tulipa "Queen of Night"', 'bulb', '🌷'],
  ['Tulip Angelique', 'Tulipa "Angelique"', 'bulb', '🌷'],
  ['Daffodil King Alfred', 'Narcissus "King Alfred"', 'bulb', '🌼'],
  ['Daffodil Tete-a-Tete', 'Narcissus "Tête-à-Tête"', 'bulb', '🌼'],
  ['Allium Purple Sensation', 'Allium hollandicum "Purple Sensation"', 'bulb', '💜'],
  ['Sunflower Autumn Beauty', 'Helianthus annuus "Autumn Beauty"', 'flowering', '🌻'],
  ['Zinnia Benary’s Giant', 'Zinnia elegans "Benary\'s Giant"', 'flowering', '🌸'],
  ['Marigold Crackerjack', 'Tagetes erecta "Crackerjack"', 'flowering', '🌼'],
  ['Cosmos Sensation', 'Cosmos bipinnatus "Sensation"', 'flowering', '🌸'],
  ['Basil Spicy Globe', 'Ocimum basilicum "Spicy Globe"', 'herb', '🌿'],
  ['Tomato Celebrity', 'Solanum lycopersicum "Celebrity"', 'vegetable', '🍅'],
  ['Cherokee Purple tomato', 'Solanum lycopersicum "Cherokee Purple"', 'vegetable', '🍅'],
  ['Mortgage Lifter tomato', 'Solanum lycopersicum "Mortgage Lifter"', 'vegetable', '🍅'],
  ['Yellow Pear tomato', 'Solanum lycopersicum "Yellow Pear"', 'vegetable', '🍅'],
  ['Pepper California Wonder', 'Capsicum annuum "California Wonder"', 'vegetable', '🫑'],
  ['Cucumber Marketmore', 'Cucumis sativus "Marketmore 76"', 'vegetable', '🥒'],
  ['Zucchini Black Beauty', 'Cucurbita pepo "Black Beauty"', 'vegetable'],
  ['Carrot Nantes', 'Daucus carota "Nantes"', 'vegetable', '🥕'],
  ['Beet Detroit Dark Red', 'Beta vulgaris "Detroit Dark Red"', 'vegetable'],
  ['Radish Cherry Belle', 'Raphanus sativus "Cherry Belle"', 'vegetable'],
  ['Lettuce Black Seeded Simpson', 'Lactuca sativa "Black Seeded Simpson"', 'vegetable', '🥬'],
  ['Corn Silver Queen', 'Zea mays "Silver Queen"', 'vegetable', '🌽'],
  ['Pumpkin Howden', 'Cucurbita pepo "Howden"', 'vegetable', '🎃'],
  ['Sugar Pie pumpkin', 'Cucurbita pepo "Small Sugar"', 'vegetable', '🎃'],
  ['Watermelon Sugar Baby', 'Citrullus lanatus "Sugar Baby"', 'vegetable', '🍉'],
  ['Strawberry Albion', 'Fragaria × ananassa "Albion"', 'flowering', '🍓'],

  // ═══════════════ MORE PERENNIALS, NATIVES & SHADE PLANTS ═══════════════
  ['Trillium', 'Trillium grandiflorum', 'flowering', '🌸'],
  ['Jack-in-the-pulpit', 'Arisaema triphyllum', 'flowering', '🌿'],
  ['Solomon’s seal', 'Polygonatum odoratum', 'flowering', '🌿'],
  ['Pasque flower', 'Pulsatilla vulgaris', 'flowering', '💜'],
  ['Rock rose', 'Helianthemum nummularium', 'flowering', '🌼'],
  ['Soapwort', 'Saponaria officinalis', 'flowering', '🌸'],
  ['Red valerian', 'Centranthus ruber', 'flowering', '🌺'],
  ['Mullein', 'Verbascum thapsus', 'flowering', '🌼'],
  ['Painted daisy', 'Tanacetum coccineum', 'flowering', '🌸'],
  ['Marguerite daisy', 'Argyranthemum frutescens', 'flowering', '🌼'],
  ['African daisy', 'Osteospermum ecklonis', 'flowering', '🌼'],
  ['Dianthus Firewitch', 'Dianthus gratianopolitanus "Firewitch"', 'flowering', '🌸'],
  ['Christmas rose', 'Helleborus niger', 'flowering', '🌸'],
  ['Bergenia', 'Bergenia cordifolia', 'flowering', '🌸'],
  ['Rodgersia', 'Rodgersia pinnata', 'flowering', '🌸'],
  ['Ligularia', 'Ligularia dentata', 'flowering', '🌼'],
  ['Astrantia', 'Astrantia major', 'flowering', '🌸'],
  ['Bloodroot', 'Sanguinaria canadensis', 'flowering', '🌸'],
  ['Virginia bluebells', 'Mertensia virginica', 'flowering', '💙'],
  ['Agapanthus', 'Agapanthus africanus', 'flowering', '💜'],
  ['New Zealand flax', 'Phormium tenax', 'grass'],
  ['Society garlic', 'Tulbaghia violacea', 'flowering', '💜'],
  ['Flax lily', 'Dianella tasmanica', 'grass'],
  ['Mat rush', 'Lomandra longifolia', 'grass'],
  ['Pentas', 'Pentas lanceolata', 'flowering', '🌸'],
  ['Blue plumbago', 'Plumbago auriculata', 'shrub', '💙'],
  ['Golden dewdrop', 'Duranta erecta', 'shrub', '💜'],
  ['Princess flower', 'Tibouchina urvilleana', 'shrub', '💜'],
  ['Ixora', 'Ixora coccinea', 'shrub', '🌺'],
  ['Sky vine', 'Thunbergia grandiflora', 'vine', '💙'],
  ['Allamanda', 'Allamanda cathartica', 'vine', '🌼'],
  ['Crossandra', 'Crossandra infundibuliformis', 'flowering', '🌺'],
  ['Firebush', 'Hamelia patens', 'shrub', '🌺'],
  ['Angel’s trumpet', 'Brugmansia suaveolens', 'shrub', '🌸'],
  ['Night blooming jasmine', 'Cestrum nocturnum', 'shrub', '🌸'],
  ['Canna Tropicanna', 'Canna "Tropicanna"', 'bulb', '🌺'],
  ['Red Abyssinian banana', 'Ensete ventricosum "Maurelii"', 'tropical'],
  ['Cordyline Red Star', 'Cordyline australis "Red Star"', 'tree'],

  // ═══════════════ GROUNDCOVERS & AQUATICS ═══════════════
  ['Pachysandra', 'Pachysandra terminalis', 'flowering', '🌿'],
  ['Periwinkle', 'Vinca minor', 'flowering', '💜'],
  ['Mazus', 'Mazus reptans', 'flowering', '💜'],
  ['Corsican mint', 'Mentha requienii', 'herb', '🌿'],
  ['Irish moss', 'Sagina subulata', 'flowering', '🌿'],
  ['Scotch moss', 'Sagina subulata "Aurea"', 'flowering', '🌿'],
  ['Blue star creeper', 'Isotoma fluviatilis', 'flowering', '💙'],
  ['Water lily', 'Nymphaea odorata', 'flowering', '🌸'],
  ['Sacred lotus', 'Nelumbo nucifera', 'flowering', '🌸'],
  ['Water lettuce', 'Pistia stratiotes', 'tropical'],
  ['Horsetail', 'Equisetum hyemale', 'grass'],
  ['Pickerel rush', 'Pontederia cordata', 'flowering', '💜'],

  // ═══════════════ MORE SHRUBS & CONIFERS ═══════════════
  ['Encore azalea', 'Rhododendron "Encore Autumn Amethyst"', 'shrub', '🌸'],
  ['PJM rhododendron', 'Rhododendron "PJM"', 'shrub', '💜'],
  ['Camellia Sasanqua', 'Camellia sasanqua', 'shrub', '🌸'],
  ['Tea plant', 'Camellia sinensis', 'shrub', '🌿'],
  ['Dwarf Alberta spruce', 'Picea glauca "Conica"', 'shrub', '🌲'],
  ['Bird’s nest spruce', 'Picea abies "Nidiformis"', 'shrub', '🌲'],
  ['Gold mop cypress', 'Chamaecyparis pisifera "Golden Mop"', 'shrub', '🌲'],
  ['Hinoki cypress', 'Chamaecyparis obtusa', 'tree', '🌲'],
  ['Blue Star juniper', 'Juniperus squamata "Blue Star"', 'shrub', '🌲'],
  ['Creeping juniper', 'Juniperus horizontalis', 'shrub', '🌲'],
  ['Emerald Green arborvitae', 'Thuja occidentalis "Smaragd"', 'tree', '🌲'],
  ['Boxwood Green Velvet', 'Buxus "Green Velvet"', 'shrub'],
  ['Japanese holly', 'Ilex crenata', 'shrub'],
  ['Yaupon holly', 'Ilex vomitoria', 'shrub'],
  ['Cherry laurel', 'Prunus laurocerasus', 'shrub'],
  ['Skip laurel', 'Prunus laurocerasus "Schipkaensis"', 'shrub'],
  ['Photinia Red Robin', 'Photinia × fraseri "Red Robin"', 'shrub'],
  ['Euonymus Emerald Gaiety', 'Euonymus fortunei "Emerald Gaiety"', 'shrub'],
  ['Wintercreeper', 'Euonymus fortunei', 'shrub'],
  ['Leyland cypress', '× Cupressocyparis leylandii', 'tree', '🌲'],
  ['Loropetalum', 'Loropetalum chinense', 'shrub', '🌸'],
  ['Laurustinus', 'Viburnum tinus', 'shrub', '🌸'],
  ['Distylium', 'Distylium "Vintage Jade"', 'shrub'],

  // ═══════════════ MORE TREES ═══════════════
  ['Coral bark maple', 'Acer palmatum "Sango-kaku"', 'tree', '🍁'],
  ['Crimson Queen Japanese maple', 'Acer palmatum "Crimson Queen"', 'tree', '🍁'],
  ['Autumn Blaze maple', 'Acer × freemanii "Autumn Blaze"', 'tree', '🍁'],
  ['October Glory maple', 'Acer rubrum "October Glory"', 'tree', '🍁'],
  ['Crimson King maple', 'Acer platanoides "Crimson King"', 'tree', '🍁'],
  ['Quaking aspen', 'Populus tremuloides', 'tree'],
  ['American sycamore', 'Platanus occidentalis', 'tree'],
  ['London plane tree', 'Platanus × acerifolia', 'tree'],
  ['Chinese pistache', 'Pistacia chinensis', 'tree'],
  ['Sweetbay magnolia', 'Magnolia virginiana', 'tree', '🌸'],
  ['Jane magnolia', 'Magnolia "Jane"', 'tree', '🌸'],
  ['Crape myrtle Natchez', 'Lagerstroemia "Natchez"', 'tree', '🌸'],
  ['Redbud Forest Pansy', 'Cercis canadensis "Forest Pansy"', 'tree', '🌸'],
  ['Fringe tree', 'Chionanthus virginicus', 'tree', '🌸'],
  ['American holly', 'Ilex opaca', 'tree'],
  ['Deodar cedar', 'Cedrus deodara', 'tree', '🌲'],
  ['Blue atlas cedar', 'Cedrus atlantica "Glauca"', 'tree', '🌲'],
  ['Japanese cedar', 'Cryptomeria japonica', 'tree', '🌲'],
  ['Canadian hemlock', 'Tsuga canadensis', 'tree', '🌲'],
  ['Douglas fir', 'Pseudotsuga menziesii', 'tree', '🌲'],
  ['Fraser fir', 'Abies fraseri', 'tree', '🌲'],
  ['Concolor fir', 'Abies concolor', 'tree', '🌲'],
  ['Giant sequoia', 'Sequoiadendron giganteum', 'tree', '🌲'],
  ['Coast redwood', 'Sequoia sempervirens', 'tree', '🌲'],
  ['Palo verde', 'Parkinsonia florida', 'tree'],
  ['Desert willow', 'Chilopsis linearis', 'tree', '🌸'],
  ['Chaste tree', 'Vitex agnus-castus', 'tree', '💜'],
  ['Silk tree', 'Albizia julibrissin', 'tree', '🌸'],
  ['Jacaranda', 'Jacaranda mimosifolia', 'tree', '💜'],
];
